Practice Exercise 1

In [ ]:
import pandas as pd
df = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/MPG.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [ ]:
df.head(8)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii

In [ ]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df.tail(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    object
 8   name          398 non-null    object
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB

In [ ]:
df.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [ ]:
df.describe(include = 'all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,usa,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,249,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,NaN,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,NaN,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,NaN,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,NaN,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,NaN,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,NaN,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,NaN,NaN

In [ ]:
df.shape

(398, 9)

In [ ]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
pd.options.display.max_rows=400
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
30,28.0,4,140.0,90.0,2264,15.5,71,usa,chevrolet vega 2300
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
32,25.0,4,98.0,NaN,2046,19.0,71,usa,ford pinto
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
34,16.0,6,225.0,105.0,3439,15.5,71,usa,plymouth satellite custom
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
36,19.0,6,250.0,88.0,3302,15.5,71,usa,ford torino 500
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador
38,14.0,8,350.0,165.0,4209,12.0,71,usa,chevrolet impala
39,14.0,8,400.0,175.0,4464,11.5,71,usa,pontiac catalina brougham
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
41,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
43,13.0,8,400.0,170.0,4746,12.0,71,usa,ford country squire (sw)
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
45,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
46,22.0,4,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
47,19.0,6,250.0,100.0,3282,15.0,71,usa,pontiac firebird
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
49,23.0,4,122.0,86.0,2220,14.0,71,usa,mercury capri 2000
50,28.0,4,116.0,90.0,2123,14.0,71,europe,opel 1900
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
55,27.0,4,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
56,26.0,4,91.0,70.0,1955,20.5,71,usa,plymouth cricket
57,24.0,4,113.0,95.0,2278,15.5,72,japan,toyota corona hardtop
58,25.0,4,97.5,80.0,2126,17.0,72,usa,dodge colt hardtop
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
61,21.0,4,122.0,86.0,2226,16.5,72,usa,ford pinto runabout
62,13.0,8,350.0,165.0,4274,12.0,72,usa,chevrolet impala
63,14.0,8,400.0,175.0,4385,12.0,72,usa,pontiac catalina
64,15.0,8,318.0,150.0,4135,13.5,72,usa,plymouth fury iii
65,14.0,8,351.0,153.0,4129,13.0,72,usa,ford galaxie 500
66,17.0,8,304.0,150.0,3672,11.5,72,usa,amc ambassador sst
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
68,13.0,8,350.0,155.0,4502,13.5,72,usa,buick lesabre custom
69,12.0,8,350.0,160.0,4456,13.5,72,usa,oldsmobile delta 88 royale
70,13.0,8,400.0,190.0,4422,12.5,72,usa,chrysler newport royal
71,19.0,3,70.0,97.0,2330,13.5,72,japan,mazda rx2 coupe
72,15.0,8,304.0,150.0,3892,12.5,72,usa,amc matador (sw)
73,13.0,8,307.0,130.0,4098,14.0,72,usa,chevrolet chevelle concours (sw)
74,13.0,8,302.0,140.0,4294,16.0,72,usa,ford gran torino (sw)
75,14.0,8,318.0,150.0,4077,14.0,72,usa,plymouth satellite custom (sw)
76,18.0,4,121.0,112.0,2933,14.5,72,europe,volvo 145e (sw)
77,22.0,4,121.0,76.0,2511,18.0,72,europe,volkswagen 411 (sw)
78,21.0,4,120.0,87.0,2979,19.5,72,europe,peugeot 504 (sw)
79,26.0,4,96.0,69.0,2189,18.0,72,europe,renault 12 (sw)
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
81,28.0,4,97.0,92.0,2288,17.0,72,japan,datsun 510 (sw)
82,23.0,4,120.0,97.0,2506,14.5,72,japan,toyouta corona mark ii (sw)
83,28.0,4,98.0,80.0,2164,15.0,72,usa,dodge colt (sw)
84,27.0,4,97.0,88.0,2100,16.5,72,japan,toyota corolla 1600 (sw)
85,13.0,8,350.0,175.0,4100,13.0,73,usa,buick century 350
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador
87,13.0,8,350.0,145.0,3988,13.0,73,usa,chevrolet malibu
88,14.0,8,302.0,137.0,4042,14.5,73,usa,ford gran torino
89,15.0,8,318.0,150.0,3777,12.5,73,usa,dodge coronet custom
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
91,13.0,8,400.0,150.0,4464,12.0,73,usa,chevrolet caprice classic
92,13.0,8,351.0,158.0,4363,13.0,73,usa,ford ltd
93,14.0,8,318.0,150.0,4237,14.5,73,usa,plymouth fury gran sedan
94,13.0,8,440.0,215.0,4735,11.0,73,usa,chrysler new yorker brougham
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
96,13.0,8,360.0,175.0,3821,11.0,73,usa,amc ambassador brougham
97,18.0,6,225.0,105.0,3121,16.5,73,usa,plymouth valiant
98,16.0,6,250.0,100.0,3278,18.0,73,usa,chevrolet nova custom
99,18.0,6,232.0,100.0,2945,16.0,73,usa,amc hornet
100,18.0,6,250.0,88.0,3021,16.5,73,usa,ford maverick
101,23.0,6,198.0,95.0,2904,16.0,73,usa,plymouth duster
102,26.0,4,97.0,46.0,1950,21.0,73,europe,volkswagen super beetle
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
104,12.0,8,400.0,167.0,4906,12.5,73,usa,ford country
105,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
106,12.0,8,350.0,180.0,4499,12.5,73,usa,oldsmobile vista cruiser
107,18.0,6,232.0,100.0,2789,15.0,73,usa,amc gremlin
108,20.0,4,97.0,88.0,2279,19.0,73,japan,toyota carina
109,21.0,4,140.0,72.0,2401,19.5,73,usa,chevrolet vega
110,22.0,4,108.0,94.0,2379,16.5,73,japan,datsun 610
111,18.0,3,70.0,90.0,2124,13.5,73,japan,maxda rx3
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
113,21.0,6,155.0,107.0,2472,14.0,73,usa,mercury capri v6
114,26.0,4,98.0,90.0,2265,15.5,73,europe,fiat 124 sport coupe
115,15.0,8,350.0,145.0,4082,13.0,73,usa,chevrolet monte carlo s
116,16.0,8,400.0,230.0,4278,9.5,73,usa,pontiac grand prix
117,29.0,4,68.0,49.0,1867,19.5,73,europe,fiat 128
118,24.0,4,116.0,75.0,2158,15.5,73,europe,opel manta
119,20.0,4,114.0,91.0,2582,14.0,73,europe,audi 100ls
120,19.0,4,121.0,112.0,2868,15.5,73,europe,volvo 144ea
121,15.0,8,318.0,150.0,3399,11.0,73,usa,dodge dart custom
122,24.0,4,121.0,110.0,2660,14.0,73,europe,saab 99le
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
124,11.0,8,350.0,180.0,3664,11.0,73,usa,oldsmobile omega
125,20.0,6,198.0,95.0,3102,16.5,74,usa,plymouth duster
126,21.0,6,200.0,NaN,2875,17.0,74,usa,ford maverick
127,19.0,6,232.0,100.0,2901,16.0,74,usa,amc hornet
128,15.0,6,250.0,100.0,3336,17.0,74,usa,chevrolet nova
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
131,32.0,4,71.0,65.0,1836,21.0,74,japan,toyota corolla 1200
132,25.0,4,140.0,75.0,2542,17.0,74,usa,chevrolet vega
133,16.0,6,250.0,100.0,3781,17.0,74,usa,chevrolet chevelle malibu classic
134,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
135,18.0,6,225.0,105.0,3613,16.5,74,usa,plymouth satellite sebring
136,16.0,8,302.0,140.0,4141,14.0,74,usa,ford gran torino
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
138,14.0,8,318.0,150.0,4457,13.5,74,usa,dodge coronet custom (sw)
139,14.0,8,302.0,140.0,4638,16.0,74,usa,ford gran torino (sw)
140,14.0,8,304.0,150.0,4257,15.5,74,usa,amc matador (sw)
141,29.0,4,98.0,83.0,2219,16.5,74,europe,audi fox
142,26.0,4,79.0,67.0,1963,15.5,74,europe,volkswagen dasher
143,26.0,4,97.0,78.0,2300,14.5,74,europe,opel manta
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
145,32.0,4,83.0,61.0,2003,19.0,74,japan,datsun 710
146,28.0,4,90.0,75.0,2125,14.5,74,usa,dodge colt
147,24.0,4,90.0,75.0,2108,15.5,74,europe,fiat 128
148,26.0,4,116.0,75.0,2246,14.0,74,europe,fiat 124 tc
149,24.0,4,120.0,97.0,2489,15.0,74,japan,honda civic
150,26.0,4,108.0,93.0,2391,15.5,74,japan,subaru
151,31.0,4,79.0,67.0,2000,16.0,74,europe,fiat x1.9
152,19.0,6,225.0,95.0,3264,16.0,75,usa,plymouth valiant custom
153,18.0,6,250.0,105.0,3459,16.0,75,usa,chevrolet nova
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch
155,15.0,6,250.0,72.0,3158,19.5,75,usa,ford maverick
156,16.0,8,400.0,170.0,4668,11.5,75,usa,pontiac catalina
157,15.0,8,350.0,145.0,4440,14.0,75,usa,chevrolet bel air
158,16.0,8,318.0,150.0,4498,14.5,75,usa,plymouth grand fury
159,14.0,8,351.0,148.0,4657,13.5,75,usa,ford ltd
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu
162,15.0,6,258.0,110.0,3730,19.0,75,usa,amc matador
163,18.0,6,225.0,95.0,3785,19.0,75,usa,plymouth fury
164,21.0,6,231.0,110.0,3039,15.0,75,usa,buick skyhawk
165,20.0,8,262.0,110.0,3221,13.5,75,usa,chevrolet monza 2+2
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii
167,29.0,4,97.0,75.0,2171,16.0,75,japan,toyota corolla
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
169,20.0,6,232.0,100.0,2914,16.0,75,usa,amc gremlin
170,23.0,4,140.0,78.0,2592,18.5,75,usa,pontiac astro
171,24.0,4,134.0,96.0,2702,13.5,75,japan,toyota corona
172,25.0,4,90.0,71.0,2223,16.5,75,europe,volkswagen dasher
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
175,29.0,4,90.0,70.0,1937,14.0,75,europe,volkswagen rabbit
176,19.0,6,232.0,90.0,3211,17.0,75,usa,amc pacer
177,23.0,4,115.0,95.0,2694,15.0,75,europe,audi 100ls
178,23.0,4,120.0,88.0,2957,17.0,75,europe,peugeot 504
179,22.0,4,121.0,98.0,2945,14.5,75,europe,volvo 244dl
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc
182,28.0,4,107.0,86.0,2464,15.5,76,europe,fiat 131
183,25.0,4,116.0,81.0,2220,16.9,76,europe,opel 1900
184,25.0,4,140.0,92.0,2572,14.9,76,usa,capri ii
185,26.0,4,98.0,79.0,2255,17.7,76,usa,dodge colt
186,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
187,17.5,8,305.0,140.0,4215,13.0,76,usa,chevrolet chevelle malibu classic
188,16.0,8,318.0,150.0,4190,13.0,76,usa,dodge coronet brougham
189,15.5,8,304.0,120.0,3962,13.9,76,usa,amc matador
190,14.5,8,351.0,152.0,4215,12.8,76,usa,ford gran torino
191,22.0,6,225.0,100.0,3233,15.4,76,usa,plymouth valiant
192,22.0,6,250.0,105.0,3353,14.5,76,usa,chevrolet nova
193,24.0,6,200.0,81.0,3012,17.6,76,usa,ford maverick
194,22.5,6,232.0,90.0,3085,17.6,76,usa,amc hornet
195,29.0,4,85.0,52.0,2035,22.2,76,usa,chevrolet chevette
196,24.5,4,98.0,60.0,2164,22.1,76,usa,chevrolet woody
197,29.0,4,90.0,70.0,1937,14.2,76,europe,vw rabbit
198,33.0,4,91.0,53.0,1795,17.4,76,japan,honda civic
199,20.0,6,225.0,100.0,3651,17.7,76,usa,dodge aspen se
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
201,18.5,6,250.0,110.0,3645,16.2,76,usa,pontiac ventura sj
202,17.5,6,258.0,95.0,3193,17.8,76,usa,amc pacer d/l
203,29.5,4,97.0,71.0,1825,12.2,76,europe,volkswagen rabbit
204,32.0,4,85.0,70.0,1990,17.0,76,japan,datsun b-210
205,28.0,4,97.0,75.0,2155,16.4,76,japan,toyota corolla
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
207,20.0,4,130.0,102.0,3150,15.7,76,europe,volvo 245
208,13.0,8,318.0,150.0,3940,13.2,76,usa,plymouth volare premier v8
209,19.0,4,120.0,88.0,3270,21.9,76,europe,peugeot 504
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
211,16.5,6,168.0,120.0,3820,16.7,76,europe,mercedes-benz 280s
212,16.5,8,350.0,180.0,4380,12.1,76,usa,cadillac seville
213,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
214,13.0,8,302.0,130.0,3870,15.0,76,usa,ford f108
215,13.0,8,318.0,150.0,3755,14.0,76,usa,dodge d100
216,31.5,4,98.0,68.0,2045,18.5,77,japan,honda accord cvcc
217,30.0,4,111.0,80.0,2155,14.8,77,usa,buick opel isuzu deluxe
218,36.0,4,79.0,58.0,1825,18.6,77,europe,renault 5 gtl
219,25.5,4,122.0,96.0,2300,15.5,77,usa,plymouth arrow gs
220,33.5,4,85.0,70.0,1945,16.8,77,japan,datsun f-10 hatchback
221,17.5,8,305.0,145.0,3880,12.5,77,usa,chevrolet caprice classic
222,17.0,8,260.0,110.0,4060,19.0,77,usa,oldsmobile cutlass supreme
223,15.5,8,318.0,145.0,4140,13.7,77,usa,dodge monaco brougham
224,15.0,8,302.0,130.0,4295,14.9,77,usa,mercury cougar brougham
225,17.5,6,250.0,110.0,3520,16.4,77,usa,chevrolet concours
226,20.5,6,231.0,105.0,3425,16.9,77,usa,buick skylark
227,19.0,6,225.0,100.0,3630,17.7,77,usa,plymouth volare custom
228,18.5,6,250.0,98.0,3525,19.0,77,usa,ford granada
229,16.0,8,400.0,180.0,4220,11.1,77,usa,pontiac grand prix lj
230,15.5,8,350.0,170.0,4165,11.4,77,usa,chevrolet monte carlo landau
231,15.5,8,400.0,190.0,4325,12.2,77,usa,chrysler cordoba
232,16.0,8,351.0,149.0,4335,14.5,77,usa,ford thunderbird
233,29.0,4,97.0,78.0,1940,14.5,77,europe,volkswagen rabbit custom
234,24.5,4,151.0,88.0,2740,16.0,77,usa,pontiac sunbird coupe
235,26.0,4,97.0,75.0,2265,18.2,77,japan,toyota corolla liftback
236,25.5,4,140.0,89.0,2755,15.8,77,usa,ford mustang ii 2+2
237,30.5,4,98.0,63.0,2051,17.0,77,usa,chevrolet chevette
238,33.5,4,98.0,83.0,2075,15.9,77,usa,dodge colt m/m
239,30.0,4,97.0,67.0,1985,16.4,77,japan,subaru dl
240,30.5,4,97.0,78.0,2190,14.1,77,europe,volkswagen dasher
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
242,21.5,4,121.0,110.0,2600,12.8,77,europe,bmw 320i
243,21.5,3,80.0,110.0,2720,13.5,77,japan,mazda rx-4
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
246,32.8,4,78.0,52.0,1985,19.4,78,japan,mazda glc deluxe
247,39.4,4,85.0,70.0,2070,18.6,78,japan,datsun b210 gx
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
249,19.9,8,260.0,110.0,3365,15.5,78,usa,oldsmobile cutlass salon brougham
250,19.4,8,318.0,140.0,3735,13.2,78,usa,dodge diplomat
251,20.2,8,302.0,139.0,3570,12.8,78,usa,mercury monarch ghia
252,19.2,6,231.0,105.0,3535,19.2,78,usa,pontiac phoenix lj
253,20.5,6,200.0,95.0,3155,18.2,78,usa,chevrolet malibu
254,20.2,6,200.0,85.0,2965,15.8,78,usa,ford fairmont (auto)
255,25.1,4,140.0,88.0,2720,15.4,78,usa,ford fairmont (man)
256,20.5,6,225.0,100.0,3430,17.2,78,usa,plymouth volare
257,19.4,6,232.0,90.0,3210,17.2,78,usa,amc concord
258,20.6,6,231.0,105.0,3380,15.8,78,usa,buick century special
259,20.8,6,200.0,85.0,3070,16.7,78,usa,mercury zephyr
260,18.6,6,225.0,110.0,3620,18.7,78,usa,dodge aspen
261,18.1,6,258.0,120.0,3410,15.1,78,usa,amc concord d/l
262,19.2,8,305.0,145.0,3425,13.2,78,usa,chevrolet monte carlo landau
263,17.7,6,231.0,165.0,3445,13.4,78,usa,buick regal sport coupe (turbo)
264,18.1,8,302.0,139.0,3205,11.2,78,usa,ford futura
265,17.5,8,318.0,140.0,4080,13.7,78,usa,dodge magnum xe
266,30.0,4,98.0,68.0,2155,16.5,78,usa,chevrolet chevette
267,27.5,4,134.0,95.0,2560,14.2,78,japan,toyota corona
268,27.2,4,119.0,97.0,2300,14.7,78,japan,datsun 510
269,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
270,21.1,4,134.0,95.0,2515,14.8,78,japan,toyota celica gt liftback
271,23.2,4,156.0,105.0,2745,16.7,78,usa,plymouth sapporo
272,23.8,4,151.0,85.0,2855,17.6,78,usa,oldsmobile starfire sx
273,23.9,4,119.0,97.0,2405,14.9,78,japan,datsun 200-sx
274,20.3,5,131.0,103.0,2830,15.9,78,europe,audi 5000
275,17.0,6,163.0,125.0,3140,13.6,78,europe,volvo 264gl
276,21.6,4,121.0,115.0,2795,15.7,78,europe,saab 99gle
277,16.2,6,163.0,133.0,3410,15.8,78,europe,peugeot 604sl
278,31.5,4,89.0,71.0,1990,14.9,78,europe,volkswagen scirocco
279,29.5,4,98.0,68.0,2135,16.6,78,japan,honda accord lx
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
281,19.8,6,200.0,85.0,2990,18.2,79,usa,mercury zephyr 6
282,22.3,4,140.0,88.0,2890,17.3,79,usa,ford fairmont 4
283,20.2,6,232.0,90.0,3265,18.2,79,usa,amc concord dl 6
284,20.6,6,225.0,110.0,3360,16.6,79,usa,dodge aspen 6
285,17.0,8,305.0,130.0,3840,15.4,79,usa,chevrolet caprice classic
286,17.6,8,302.0,129.0,3725,13.4,79,usa,ford ltd landau
287,16.5,8,351.0,138.0,3955,13.2,79,usa,mercury grand marquis
288,18.2,8,318.0,135.0,3830,15.2,79,usa,dodge st. regis
289,16.9,8,350.0,155.0,4360,14.9,79,usa,buick estate wagon (sw)
290,15.5,8,351.0,142.0,4054,14.3,79,usa,ford country squire (sw)
291,19.2,8,267.0,125.0,3605,15.0,79,usa,chevrolet malibu classic (sw)
292,18.5,8,360.0,150.0,3940,13.0,79,usa,chrysler lebaron town @ country (sw)
293,31.9,4,89.0,71.0,1925,14.0,79,europe,vw rabbit custom
294,34.1,4,86.0,65.0,1975,15.2,79,japan,maxda glc deluxe
295,35.7,4,98.0,80.0,1915,14.4,79,usa,dodge colt hatchback custom
296,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
297,25.4,5,183.0,77.0,3530,20.1,79,europe,mercedes benz 300d
298,23.0,8,350.0,125.0,3900,17.4,79,usa,cadillac eldorado
299,27.2,4,141.0,71.0,3190,24.8,79,europe,peugeot 504
300,23.9,8,260.0,90.0,3420,22.2,79,usa,oldsmobile cutlass salon brougham
301,34.2,4,105.0,70.0,2200,13.2,79,usa,plymouth horizon
302,34.5,4,105.0,70.0,2150,14.9,79,usa,plymouth horizon tc3
303,31.8,4,85.0,65.0,2020,19.2,79,japan,datsun 210
304,37.3,4,91.0,69.0,2130,14.7,79,europe,fiat strada custom
305,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited
306,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
307,26.8,6,173.0,115.0,2700,12.9,79,usa,oldsmobile omega brougham
308,33.5,4,151.0,90.0,2556,13.2,79,usa,pontiac phoenix
309,41.5,4,98.0,76.0,2144,14.7,80,europe,vw rabbit
310,38.1,4,89.0,60.0,1968,18.8,80,japan,toyota corolla tercel
311,32.1,4,98.0,70.0,2120,15.5,80,usa,chevrolet chevette
312,37.2,4,86.0,65.0,2019,16.4,80,japan,datsun 310
313,28.0,4,151.0,90.0,2678,16.5,80,usa,chevrolet citation
314,26.4,4,140.0,88.0,2870,18.1,80,usa,ford fairmont
315,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
316,19.1,6,225.0,90.0,3381,18.7,80,usa,dodge aspen
317,34.3,4,97.0,78.0,2188,15.8,80,europe,audi 4000
318,29.8,4,134.0,90.0,2711,15.5,80,japan,toyota corona liftback
319,31.3,4,120.0,75.0,2542,17.5,80,japan,mazda 626
320,37.0,4,119.0,92.0,2434,15.0,80,japan,datsun 510 hatchback
321,32.2,4,108.0,75.0,2265,15.2,80,japan,toyota corolla
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
323,27.9,4,156.0,105.0,2800,14.4,80,usa,dodge colt
324,40.8,4,85.0,65.0,2110,19.2,80,japan,datsun 210
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
327,36.4,5,121.0,67.0,2950,19.9,80,europe,audi 5000s (diesel)
328,30.0,4,146.0,67.0,3250,21.8,80,europe,mercedes-benz 240d
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
330,40.9,4,85.0,NaN,1835,17.3,80,europe,renault lecar deluxe
331,33.8,4,97.0,67.0,2145,18.0,80,japan,subaru dl
332,29.8,4,89.0,62.0,1845,15.3,80,europe,vokswagen rabbit
333,32.7,6,168.0,132.0,2910,11.4,80,japan,datsun 280-zx
334,23.7,3,70.0,100.0,2420,12.5,80,japan,mazda rx-7 gs
335,35.0,4,122.0,88.0,2500,15.1,80,europe,triumph tr7 coupe
336,23.6,4,140.0,NaN,2905,14.3,80,usa,ford mustang cobra
337,32.4,4,107.0,72.0,2290,17.0,80,japan,honda accord
338,27.2,4,135.0,84.0,2490,15.7,81,usa,plymouth reliant
339,26.6,4,151.0,84.0,2635,16.4,81,usa,buick skylark
340,25.8,4,156.0,92.0,2620,14.4,81,usa,dodge aries wagon (sw)
341,23.5,6,173.0,110.0,2725,12.6,81,usa,chevrolet citation
342,30.0,4,135.0,84.0,2385,12.9,81,usa,plymouth reliant
343,39.1,4,79.0,58.0,1755,16.9,81,japan,toyota starlet
344,39.0,4,86.0,64.0,1875,16.4,81,usa,plymouth champ
345,35.1,4,81.0,60.0,1760,16.1,81,japan,honda civic 1300
346,32.3,4,97.0,67.0,2065,17.8,81,japan,subaru
347,37.0,4,85.0,65.0,1975,19.4,81,japan,datsun 210 mpg
348,37.7,4,89.0,62.0,2050,17.3,81,japan,toyota tercel
349,34.1,4,91.0,68.0,1985,16.0,81,japan,mazda glc 4

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

Practice Exercise 2

In [ ]:
car=df.copy()
car

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
30,28.0,4,140.0,90.0,2264,15.5,71,usa,chevrolet vega 2300
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
34,16.0,6,225.0,105.0,3439,15.5,71,usa,plymouth satellite custom
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
36,19.0,6,250.0,88.0,3302,15.5,71,usa,ford torino 500
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador
38,14.0,8,350.0,165.0,4209,12.0,71,usa,chevrolet impala
39,14.0,8,400.0,175.0,4464,11.5,71,usa,pontiac catalina brougham
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
41,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
43,13.0,8,400.0,170.0,4746,12.0,71,usa,ford country squire (sw)
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
45,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
46,22.0,4,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
47,19.0,6,250.0,100.0,3282,15.0,71,usa,pontiac firebird
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
49,23.0,4,122.0,86.0,2220,14.0,71,usa,mercury capri 2000
50,28.0,4,116.0,90.0,2123,14.0,71,europe,opel 1900
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
55,27.0,4,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
56,26.0,4,91.0,70.0,1955,20.5,71,usa,plymouth cricket
57,24.0,4,113.0,95.0,2278,15.5,72,japan,toyota corona hardtop
58,25.0,4,97.5,80.0,2126,17.0,72,usa,dodge colt hardtop
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
61,21.0,4,122.0,86.0,2226,16.5,72,usa,ford pinto runabout
62,13.0,8,350.0,165.0,4274,12.0,72,usa,chevrolet impala
63,14.0,8,400.0,175.0,4385,12.0,72,usa,pontiac catalina
64,15.0,8,318.0,150.0,4135,13.5,72,usa,plymouth fury iii
65,14.0,8,351.0,153.0,4129,13.0,72,usa,ford galaxie 500
66,17.0,8,304.0,150.0,3672,11.5,72,usa,amc ambassador sst
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
68,13.0,8,350.0,155.0,4502,13.5,72,usa,buick lesabre custom
69,12.0,8,350.0,160.0,4456,13.5,72,usa,oldsmobile delta 88 royale
70,13.0,8,400.0,190.0,4422,12.5,72,usa,chrysler newport royal
71,19.0,3,70.0,97.0,2330,13.5,72,japan,mazda rx2 coupe
72,15.0,8,304.0,150.0,3892,12.5,72,usa,amc matador (sw)
73,13.0,8,307.0,130.0,4098,14.0,72,usa,chevrolet chevelle concours (sw)
74,13.0,8,302.0,140.0,4294,16.0,72,usa,ford gran torino (sw)
75,14.0,8,318.0,150.0,4077,14.0,72,usa,plymouth satellite custom (sw)
76,18.0,4,121.0,112.0,2933,14.5,72,europe,volvo 145e (sw)
77,22.0,4,121.0,76.0,2511,18.0,72,europe,volkswagen 411 (sw)
78,21.0,4,120.0,87.0,2979,19.5,72,europe,peugeot 504 (sw)
79,26.0,4,96.0,69.0,2189,18.0,72,europe,renault 12 (sw)
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
81,28.0,4,97.0,92.0,2288,17.0,72,japan,datsun 510 (sw)
82,23.0,4,120.0,97.0,2506,14.5,72,japan,toyouta corona mark ii (sw)
83,28.0,4,98.0,80.0,2164,15.0,72,usa,dodge colt (sw)
84,27.0,4,97.0,88.0,2100,16.5,72,japan,toyota corolla 1600 (sw)
85,13.0,8,350.0,175.0,4100,13.0,73,usa,buick century 350
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador
87,13.0,8,350.0,145.0,3988,13.0,73,usa,chevrolet malibu
88,14.0,8,302.0,137.0,4042,14.5,73,usa,ford gran torino
89,15.0,8,318.0,150.0,3777,12.5,73,usa,dodge coronet custom
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
91,13.0,8,400.0,150.0,4464,12.0,73,usa,chevrolet caprice classic
92,13.0,8,351.0,158.0,4363,13.0,73,usa,ford ltd
93,14.0,8,318.0,150.0,4237,14.5,73,usa,plymouth fury gran sedan
94,13.0,8,440.0,215.0,4735,11.0,73,usa,chrysler new yorker brougham
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
96,13.0,8,360.0,175.0,3821,11.0,73,usa,amc ambassador brougham
97,18.0,6,225.0,105.0,3121,16.5,73,usa,plymouth valiant
98,16.0,6,250.0,100.0,3278,18.0,73,usa,chevrolet nova custom
99,18.0,6,232.0,100.0,2945,16.0,73,usa,amc hornet
100,18.0,6,250.0,88.0,3021,16.5,73,usa,ford maverick
101,23.0,6,198.0,95.0,2904,16.0,73,usa,plymouth duster
102,26.0,4,97.0,46.0,1950,21.0,73,europe,volkswagen super beetle
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
104,12.0,8,400.0,167.0,4906,12.5,73,usa,ford country
105,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
106,12.0,8,350.0,180.0,4499,12.5,73,usa,oldsmobile vista cruiser
107,18.0,6,232.0,100.0,2789,15.0,73,usa,amc gremlin
108,20.0,4,97.0,88.0,2279,19.0,73,japan,toyota carina
109,21.0,4,140.0,72.0,2401,19.5,73,usa,chevrolet vega
110,22.0,4,108.0,94.0,2379,16.5,73,japan,datsun 610
111,18.0,3,70.0,90.0,2124,13.5,73,japan,maxda rx3
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
113,21.0,6,155.0,107.0,2472,14.0,73,usa,mercury capri v6
114,26.0,4,98.0,90.0,2265,15.5,73,europe,fiat 124 sport coupe
115,15.0,8,350.0,145.0,4082,13.0,73,usa,chevrolet monte carlo s
116,16.0,8,400.0,230.0,4278,9.5,73,usa,pontiac grand prix
117,29.0,4,68.0,49.0,1867,19.5,73,europe,fiat 128
118,24.0,4,116.0,75.0,2158,15.5,73,europe,opel manta
119,20.0,4,114.0,91.0,2582,14.0,73,europe,audi 100ls
120,19.0,4,121.0,112.0,2868,15.5,73,europe,volvo 144ea
121,15.0,8,318.0,150.0,3399,11.0,73,usa,dodge dart custom
122,24.0,4,121.0,110.0,2660,14.0,73,europe,saab 99le
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
124,11.0,8,350.0,180.0,3664,11.0,73,usa,oldsmobile omega
125,20.0,6,198.0,95.0,3102,16.5,74,usa,plymouth duster
127,19.0,6,232.0,100.0,2901,16.0,74,usa,amc hornet
128,15.0,6,250.0,100.0,3336,17.0,74,usa,chevrolet nova
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
131,32.0,4,71.0,65.0,1836,21.0,74,japan,toyota corolla 1200
132,25.0,4,140.0,75.0,2542,17.0,74,usa,chevrolet vega
133,16.0,6,250.0,100.0,3781,17.0,74,usa,chevrolet chevelle malibu classic
134,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
135,18.0,6,225.0,105.0,3613,16.5,74,usa,plymouth satellite sebring
136,16.0,8,302.0,140.0,4141,14.0,74,usa,ford gran torino
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
138,14.0,8,318.0,150.0,4457,13.5,74,usa,dodge coronet custom (sw)
139,14.0,8,302.0,140.0,4638,16.0,74,usa,ford gran torino (sw)
140,14.0,8,304.0,150.0,4257,15.5,74,usa,amc matador (sw)
141,29.0,4,98.0,83.0,2219,16.5,74,europe,audi fox
142,26.0,4,79.0,67.0,1963,15.5,74,europe,volkswagen dasher
143,26.0,4,97.0,78.0,2300,14.5,74,europe,opel manta
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
145,32.0,4,83.0,61.0,2003,19.0,74,japan,datsun 710
146,28.0,4,90.0,75.0,2125,14.5,74,usa,dodge colt
147,24.0,4,90.0,75.0,2108,15.5,74,europe,fiat 128
148,26.0,4,116.0,75.0,2246,14.0,74,europe,fiat 124 tc
149,24.0,4,120.0,97.0,2489,15.0,74,japan,honda civic
150,26.0,4,108.0,93.0,2391,15.5,74,japan,subaru
151,31.0,4,79.0,67.0,2000,16.0,74,europe,fiat x1.9
152,19.0,6,225.0,95.0,3264,16.0,75,usa,plymouth valiant custom
153,18.0,6,250.0,105.0,3459,16.0,75,usa,chevrolet nova
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch
155,15.0,6,250.0,72.0,3158,19.5,75,usa,ford maverick
156,16.0,8,400.0,170.0,4668,11.5,75,usa,pontiac catalina
157,15.0,8,350.0,145.0,4440,14.0,75,usa,chevrolet bel air
158,16.0,8,318.0,150.0,4498,14.5,75,usa,plymouth grand fury
159,14.0,8,351.0,148.0,4657,13.5,75,usa,ford ltd
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu
162,15.0,6,258.0,110.0,3730,19.0,75,usa,amc matador
163,18.0,6,225.0,95.0,3785,19.0,75,usa,plymouth fury
164,21.0,6,231.0,110.0,3039,15.0,75,usa,buick skyhawk
165,20.0,8,262.0,110.0,3221,13.5,75,usa,chevrolet monza 2+2
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii
167,29.0,4,97.0,75.0,2171,16.0,75,japan,toyota corolla
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
169,20.0,6,232.0,100.0,2914,16.0,75,usa,amc gremlin
170,23.0,4,140.0,78.0,2592,18.5,75,usa,pontiac astro
171,24.0,4,134.0,96.0,2702,13.5,75,japan,toyota corona
172,25.0,4,90.0,71.0,2223,16.5,75,europe,volkswagen dasher
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
175,29.0,4,90.0,70.0,1937,14.0,75,europe,volkswagen rabbit
176,19.0,6,232.0,90.0,3211,17.0,75,usa,amc pacer
177,23.0,4,115.0,95.0,2694,15.0,75,europe,audi 100ls
178,23.0,4,120.0,88.0,2957,17.0,75,europe,peugeot 504
179,22.0,4,121.0,98.0,2945,14.5,75,europe,volvo 244dl
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc
182,28.0,4,107.0,86.0,2464,15.5,76,europe,fiat 131
183,25.0,4,116.0,81.0,2220,16.9,76,europe,opel 1900
184,25.0,4,140.0,92.0,2572,14.9,76,usa,capri ii
185,26.0,4,98.0,79.0,2255,17.7,76,usa,dodge colt
186,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
187,17.5,8,305.0,140.0,4215,13.0,76,usa,chevrolet chevelle malibu classic
188,16.0,8,318.0,150.0,4190,13.0,76,usa,dodge coronet brougham
189,15.5,8,304.0,120.0,3962,13.9,76,usa,amc matador
190,14.5,8,351.0,152.0,4215,12.8,76,usa,ford gran torino
191,22.0,6,225.0,100.0,3233,15.4,76,usa,plymouth valiant
192,22.0,6,250.0,105.0,3353,14.5,76,usa,chevrolet nova
193,24.0,6,200.0,81.0,3012,17.6,76,usa,ford maverick
194,22.5,6,232.0,90.0,3085,17.6,76,usa,amc hornet
195,29.0,4,85.0,52.0,2035,22.2,76,usa,chevrolet chevette
196,24.5,4,98.0,60.0,2164,22.1,76,usa,chevrolet woody
197,29.0,4,90.0,70.0,1937,14.2,76,europe,vw rabbit
198,33.0,4,91.0,53.0,1795,17.4,76,japan,honda civic
199,20.0,6,225.0,100.0,3651,17.7,76,usa,dodge aspen se
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
201,18.5,6,250.0,110.0,3645,16.2,76,usa,pontiac ventura sj
202,17.5,6,258.0,95.0,3193,17.8,76,usa,amc pacer d/l
203,29.5,4,97.0,71.0,1825,12.2,76,europe,volkswagen rabbit
204,32.0,4,85.0,70.0,1990,17.0,76,japan,datsun b-210
205,28.0,4,97.0,75.0,2155,16.4,76,japan,toyota corolla
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
207,20.0,4,130.0,102.0,3150,15.7,76,europe,volvo 245
208,13.0,8,318.0,150.0,3940,13.2,76,usa,plymouth volare premier v8
209,19.0,4,120.0,88.0,3270,21.9,76,europe,peugeot 504
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
211,16.5,6,168.0,120.0,3820,16.7,76,europe,mercedes-benz 280s
212,16.5,8,350.0,180.0,4380,12.1,76,usa,cadillac seville
213,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
214,13.0,8,302.0,130.0,3870,15.0,76,usa,ford f108
215,13.0,8,318.0,150.0,3755,14.0,76,usa,dodge d100
216,31.5,4,98.0,68.0,2045,18.5,77,japan,honda accord cvcc
217,30.0,4,111.0,80.0,2155,14.8,77,usa,buick opel isuzu deluxe
218,36.0,4,79.0,58.0,1825,18.6,77,europe,renault 5 gtl
219,25.5,4,122.0,96.0,2300,15.5,77,usa,plymouth arrow gs
220,33.5,4,85.0,70.0,1945,16.8,77,japan,datsun f-10 hatchback
221,17.5,8,305.0,145.0,3880,12.5,77,usa,chevrolet caprice classic
222,17.0,8,260.0,110.0,4060,19.0,77,usa,oldsmobile cutlass supreme
223,15.5,8,318.0,145.0,4140,13.7,77,usa,dodge monaco brougham
224,15.0,8,302.0,130.0,4295,14.9,77,usa,mercury cougar brougham
225,17.5,6,250.0,110.0,3520,16.4,77,usa,chevrolet concours
226,20.5,6,231.0,105.0,3425,16.9,77,usa,buick skylark
227,19.0,6,225.0,100.0,3630,17.7,77,usa,plymouth volare custom
228,18.5,6,250.0,98.0,3525,19.0,77,usa,ford granada
229,16.0,8,400.0,180.0,4220,11.1,77,usa,pontiac grand prix lj
230,15.5,8,350.0,170.0,4165,11.4,77,usa,chevrolet monte carlo landau
231,15.5,8,400.0,190.0,4325,12.2,77,usa,chrysler cordoba
232,16.0,8,351.0,149.0,4335,14.5,77,usa,ford thunderbird
233,29.0,4,97.0,78.0,1940,14.5,77,europe,volkswagen rabbit custom
234,24.5,4,151.0,88.0,2740,16.0,77,usa,pontiac sunbird coupe
235,26.0,4,97.0,75.0,2265,18.2,77,japan,toyota corolla liftback
236,25.5,4,140.0,89.0,2755,15.8,77,usa,ford mustang ii 2+2
237,30.5,4,98.0,63.0,2051,17.0,77,usa,chevrolet chevette
238,33.5,4,98.0,83.0,2075,15.9,77,usa,dodge colt m/m
239,30.0,4,97.0,67.0,1985,16.4,77,japan,subaru dl
240,30.5,4,97.0,78.0,2190,14.1,77,europe,volkswagen dasher
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
242,21.5,4,121.0,110.0,2600,12.8,77,europe,bmw 320i
243,21.5,3,80.0,110.0,2720,13.5,77,japan,mazda rx-4
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
246,32.8,4,78.0,52.0,1985,19.4,78,japan,mazda glc deluxe
247,39.4,4,85.0,70.0,2070,18.6,78,japan,datsun b210 gx
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
249,19.9,8,260.0,110.0,3365,15.5,78,usa,oldsmobile cutlass salon brougham
250,19.4,8,318.0,140.0,3735,13.2,78,usa,dodge diplomat
251,20.2,8,302.0,139.0,3570,12.8,78,usa,mercury monarch ghia
252,19.2,6,231.0,105.0,3535,19.2,78,usa,pontiac phoenix lj
253,20.5,6,200.0,95.0,3155,18.2,78,usa,chevrolet malibu
254,20.2,6,200.0,85.0,2965,15.8,78,usa,ford fairmont (auto)
255,25.1,4,140.0,88.0,2720,15.4,78,usa,ford fairmont (man)
256,20.5,6,225.0,100.0,3430,17.2,78,usa,plymouth volare
257,19.4,6,232.0,90.0,3210,17.2,78,usa,amc concord
258,20.6,6,231.0,105.0,3380,15.8,78,usa,buick century special
259,20.8,6,200.0,85.0,3070,16.7,78,usa,mercury zephyr
260,18.6,6,225.0,110.0,3620,18.7,78,usa,dodge aspen
261,18.1,6,258.0,120.0,3410,15.1,78,usa,amc concord d/l
262,19.2,8,305.0,145.0,3425,13.2,78,usa,chevrolet monte carlo landau
263,17.7,6,231.0,165.0,3445,13.4,78,usa,buick regal sport coupe (turbo)
264,18.1,8,302.0,139.0,3205,11.2,78,usa,ford futura
265,17.5,8,318.0,140.0,4080,13.7,78,usa,dodge magnum xe
266,30.0,4,98.0,68.0,2155,16.5,78,usa,chevrolet chevette
267,27.5,4,134.0,95.0,2560,14.2,78,japan,toyota corona
268,27.2,4,119.0,97.0,2300,14.7,78,japan,datsun 510
269,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
270,21.1,4,134.0,95.0,2515,14.8,78,japan,toyota celica gt liftback
271,23.2,4,156.0,105.0,2745,16.7,78,usa,plymouth sapporo
272,23.8,4,151.0,85.0,2855,17.6,78,usa,oldsmobile starfire sx
273,23.9,4,119.0,97.0,2405,14.9,78,japan,datsun 200-sx
274,20.3,5,131.0,103.0,2830,15.9,78,europe,audi 5000
275,17.0,6,163.0,125.0,3140,13.6,78,europe,volvo 264gl
276,21.6,4,121.0,115.0,2795,15.7,78,europe,saab 99gle
277,16.2,6,163.0,133.0,3410,15.8,78,europe,peugeot 604sl
278,31.5,4,89.0,71.0,1990,14.9,78,europe,volkswagen scirocco
279,29.5,4,98.0,68.0,2135,16.6,78,japan,honda accord lx
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
281,19.8,6,200.0,85.0,2990,18.2,79,usa,mercury zephyr 6
282,22.3,4,140.0,88.0,2890,17.3,79,usa,ford fairmont 4
283,20.2,6,232.0,90.0,3265,18.2,79,usa,amc concord dl 6
284,20.6,6,225.0,110.0,3360,16.6,79,usa,dodge aspen 6
285,17.0,8,305.0,130.0,3840,15.4,79,usa,chevrolet caprice classic
286,17.6,8,302.0,129.0,3725,13.4,79,usa,ford ltd landau
287,16.5,8,351.0,138.0,3955,13.2,79,usa,mercury grand marquis
288,18.2,8,318.0,135.0,3830,15.2,79,usa,dodge st. regis
289,16.9,8,350.0,155.0,4360,14.9,79,usa,buick estate wagon (sw)
290,15.5,8,351.0,142.0,4054,14.3,79,usa,ford country squire (sw)
291,19.2,8,267.0,125.0,3605,15.0,79,usa,chevrolet malibu classic (sw)
292,18.5,8,360.0,150.0,3940,13.0,79,usa,chrysler lebaron town @ country (sw)
293,31.9,4,89.0,71.0,1925,14.0,79,europe,vw rabbit custom
294,34.1,4,86.0,65.0,1975,15.2,79,japan,maxda glc deluxe
295,35.7,4,98.0,80.0,1915,14.4,79,usa,dodge colt hatchback custom
296,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
297,25.4,5,183.0,77.0,3530,20.1,79,europe,mercedes benz 300d
298,23.0,8,350.0,125.0,3900,17.4,79,usa,cadillac eldorado
299,27.2,4,141.0,71.0,3190,24.8,79,europe,peugeot 504
300,23.9,8,260.0,90.0,3420,22.2,79,usa,oldsmobile cutlass salon brougham
301,34.2,4,105.0,70.0,2200,13.2,79,usa,plymouth horizon
302,34.5,4,105.0,70.0,2150,14.9,79,usa,plymouth horizon tc3
303,31.8,4,85.0,65.0,2020,19.2,79,japan,datsun 210
304,37.3,4,91.0,69.0,2130,14.7,79,europe,fiat strada custom
305,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited
306,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
307,26.8,6,173.0,115.0,2700,12.9,79,usa,oldsmobile omega brougham
308,33.5,4,151.0,90.0,2556,13.2,79,usa,pontiac phoenix
309,41.5,4,98.0,76.0,2144,14.7,80,europe,vw rabbit
310,38.1,4,89.0,60.0,1968,18.8,80,japan,toyota corolla tercel
311,32.1,4,98.0,70.0,2120,15.5,80,usa,chevrolet chevette
312,37.2,4,86.0,65.0,2019,16.4,80,japan,datsun 310
313,28.0,4,151.0,90.0,2678,16.5,80,usa,chevrolet citation
314,26.4,4,140.0,88.0,2870,18.1,80,usa,ford fairmont
315,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
316,19.1,6,225.0,90.0,3381,18.7,80,usa,dodge aspen
317,34.3,4,97.0,78.0,2188,15.8,80,europe,audi 4000
318,29.8,4,134.0,90.0,2711,15.5,80,japan,toyota corona liftback
319,31.3,4,120.0,75.0,2542,17.5,80,japan,mazda 626
320,37.0,4,119.0,92.0,2434,15.0,80,japan,datsun 510 hatchback
321,32.2,4,108.0,75.0,2265,15.2,80,japan,toyota corolla
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
323,27.9,4,156.0,105.0,2800,14.4,80,usa,dodge colt
324,40.8,4,85.0,65.0,2110,19.2,80,japan,datsun 210
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
327,36.4,5,121.0,67.0,2950,19.9,80,europe,audi 5000s (diesel)
328,30.0,4,146.0,67.0,3250,21.8,80,europe,mercedes-benz 240d
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
331,33.8,4,97.0,67.0,2145,18.0,80,japan,subaru dl
332,29.8,4,89.0,62.0,1845,15.3,80,europe,vokswagen rabbit
333,32.7,6,168.0,132.0,2910,11.4,80,japan,datsun 280-zx
334,23.7,3,70.0,100.0,2420,12.5,80,japan,mazda rx-7 gs
335,35.0,4,122.0,88.0,2500,15.1,80,europe,triumph tr7 coupe
337,32.4,4,107.0,72.0,2290,17.0,80,japan,honda accord
338,27.2,4,135.0,84.0,2490,15.7,81,usa,plymouth reliant
339,26.6,4,151.0,84.0,2635,16.4,81,usa,buick skylark
340,25.8,4,156.0,92.0,2620,14.4,81,usa,dodge aries wagon (sw)
341,23.5,6,173.0,110.0,2725,12.6,81,usa,chevrolet citation
342,30.0,4,135.0,84.0,2385,12.9,81,usa,plymouth reliant
343,39.1,4,79.0,58.0,1755,16.9,81,japan,toyota starlet
344,39.0,4,86.0,64.0,1875,16.4,81,usa,plymouth champ
345,35.1,4,81.0,60.0,1760,16.1,81,japan,honda civic 1300
346,32.3,4,97.0,67.0,2065,17.8,81,japan,subaru
347,37.0,4,85.0,65.0,1975,19.4,81,japan,datsun 210 mpg
348,37.7,4,89.0,62.0,2050,17.3,81,japan,toyota tercel
349,34.1,4,91.0,68.0,1985,16.0,81,japan,mazda glc 4
350,34.7,4,105.0,63.0,2215,14.9,81,usa,plymouth horizon 4
351,34.4,4,98.0,65.0,2045,16.2,81,usa,ford escort 4w
352,29.9,4,98.0,65.0,2380,20.7,81,usa,ford escort 2h
353,33.0,4,105.0,74.0,2190,14.2,81,europe,volkswagen jetta

In [ ]:
df.columns

Index(['mpg', 'displacement', 'horsepower', 'acceleration', 'model_year',
       'origin', 'name'],
      dtype='object')

In [ ]:
df = df.drop('model_year', axis = 1)

In [ ]:
df.columns

Index(['mpg', 'displacement', 'horsepower', 'acceleration', 'origin', 'name'], dtype='object')

In [ ]:
car.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [ ]:
car[['cylinders', 'origin']].value_counts()

cylinders  origin
8          usa       103
6          usa        73
4          japan      69
           usa        69
           europe     61
6          japan       6
3          japan       4
6          europe      4
5          europe      3
dtype: int64

In [ ]:
car['origin'].value_counts()

usa       245
japan      79
europe     68
Name: origin, dtype: int64

In [ ]:
car['origin'].unique()

array(['usa', 'japan', 'europe'], dtype=object)

In [ ]:
car['origin'].nunique()

3

In [ ]:
car.sort_values('displacement')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
117,29.0,4,68.0,49.0,1867,19.5,73,europe,fiat 128
334,23.7,3,70.0,100.0,2420,12.5,80,japan,mazda rx-7 gs
111,18.0,3,70.0,90.0,2124,13.5,73,japan,maxda rx3
71,19.0,3,70.0,97.0,2330,13.5,72,japan,mazda rx2 coupe
53,31.0,4,71.0,65.0,1773,19.0,71,japan,toyota corolla 1200
131,32.0,4,71.0,65.0,1836,21.0,74,japan,toyota corolla 1200
54,35.0,4,72.0,69.0,1613,18.0,71,japan,datsun 1200
144,31.0,4,76.0,52.0,1649,16.5,74,japan,toyota corona
246,32.8,4,78.0,52.0,1985,19.4,78,japan,mazda glc deluxe
51,30.0,4,79.0,70.0,2074,19.5,71,europe,peugeot 304
218,36.0,4,79.0,58.0,1825,18.6,77,europe,renault 5 gtl
151,31.0,4,79.0,67.0,2000,16.0,74,europe,fiat x1.9
343,39.1,4,79.0,58.0,1755,16.9,81,japan,toyota starlet
129,31.0,4,79.0,67.0,1950,19.0,74,japan,datsun b210
142,26.0,4,79.0,67.0,1963,15.5,74,europe,volkswagen dasher
243,21.5,3,80.0,110.0,2720,13.5,77,japan,mazda rx-4
345,35.1,4,81.0,60.0,1760,16.1,81,japan,honda civic 1300
145,32.0,4,83.0,61.0,2003,19.0,74,japan,datsun 710
303,31.8,4,85.0,65.0,2020,19.2,79,japan,datsun 210
247,39.4,4,85.0,70.0,2070,18.6,78,japan,datsun b210 gx
347,37.0,4,85.0,65.0,1975,19.4,81,japan,datsun 210 mpg
324,40.8,4,85.0,65.0,2110,19.2,80,japan,datsun 210
195,29.0,4,85.0,52.0,2035,22.2,76,usa,chevrolet chevette
204,32.0,4,85.0,70.0,1990,17.0,76,japan,datsun b-210
220,33.5,4,85.0,70.0,1945,16.8,77,japan,datsun f-10 hatchback
322,46.6,4,86.0,65.0,2110,17.9,80,japan,mazda glc
344,39.0,4,86.0,64.0,1875,16.4,81,usa,plymouth champ
294,34.1,4,86.0,65.0,1975,15.2,79,japan,maxda glc deluxe
312,37.2,4,86.0,65.0,2019,16.4,80,japan,datsun 310
52,30.0,4,88.0,76.0,2065,14.5,71,europe,fiat 124b
278,31.5,4,89.0,71.0,1990,14.9,78,europe,volkswagen scirocco
293,31.9,4,89.0,71.0,1925,14.0,79,europe,vw rabbit custom
332,29.8,4,89.0,62.0,1845,15.3,80,europe,vokswagen rabbit
348,37.7,4,89.0,62.0,2050,17.3,81,japan,toyota tercel
310,38.1,4,89.0,60.0,1968,18.8,80,japan,toyota corolla tercel
244,43.1,4,90.0,48.0,1985,21.5,78,europe,volkswagen rabbit custom diesel
325,44.3,4,90.0,48.0,2085,21.7,80,europe,vw rabbit c (diesel)
326,43.4,4,90.0,48.0,2335,23.7,80,europe,vw dasher (diesel)
197,29.0,4,90.0,70.0,1937,14.2,76,europe,vw rabbit
172,25.0,4,90.0,71.0,2223,16.5,75,europe,volkswagen dasher
146,28.0,4,90.0,75.0,2125,14.5,74,usa,dodge colt
147,24.0,4,90.0,75.0,2108,15.5,74,europe,fiat 128
175,29.0,4,90.0,70.0,1937,14.0,75,europe,volkswagen rabbit
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
377,31.0,4,91.0,68.0,1970,17.6,82,japan,mazda glc custom
376,37.0,4,91.0,68.0,2025,18.2,82,japan,mazda glc custom l
304,37.3,4,91.0,69.0,2130,14.7,79,europe,fiat strada custom
56,26.0,4,91.0,70.0,1955,20.5,71,usa,plymouth cricket
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
349,34.1,4,91.0,68.0,1985,16.0,81,japan,mazda glc 4
198,33.0,4,91.0,53.0,1795,17.4,76,japan,honda civic
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc
79,26.0,4,96.0,69.0,2189,18.0,72,europe,renault 12 (sw)
84,27.0,4,97.0,88.0,2100,16.5,72,japan,toyota corolla 1600 (sw)
240,30.5,4,97.0,78.0,2190,14.1,77,europe,volkswagen dasher
239,30.0,4,97.0,67.0,1985,16.4,77,japan,subaru dl
102,26.0,4,97.0,46.0,1950,21.0,73,europe,volkswagen super beetle
143,26.0,4,97.0,78.0,2300,14.5,74,europe,opel manta
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
235,26.0,4,97.0,75.0,2265,18.2,77,japan,toyota corolla liftback
81,28.0,4,97.0,92.0,2288,17.0,72,japan,datsun 510 (sw)
331,33.8,4,97.0,67.0,2145,18.0,80,japan,subaru dl
346,32.3,4,97.0,67.0,2065,17.8,81,japan,subaru
233,29.0,4,97.0,78.0,1940,14.5,77,europe,volkswagen rabbit custom
167,29.0,4,97.0,75.0,2171,16.0,75,japan,toyota corolla
203,29.5,4,97.0,71.0,1825,12.2,76,europe,volkswagen rabbit
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
317,34.3,4,97.0,78.0,2188,15.8,80,europe,audi 4000
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
55,27.0,4,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
108,20.0,4,97.0,88.0,2279,19.0,73,japan,toyota carina
205,28.0,4,97.0,75.0,2155,16.4,76,japan,toyota corolla
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
58,25.0,4,97.5,80.0,2126,17.0,72,usa,dodge colt hardtop
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
114,26.0,4,98.0,90.0,2265,15.5,73,europe,fiat 124 sport coupe
196,24.5,4,98.0,60.0,2164,22.1,76,usa,chevrolet woody
185,26.0,4,98.0,79.0,2255,17.7,76,usa,dodge colt
216,31.5,4,98.0,68.0,2045,18.5,77,japan,honda accord cvcc
238,33.5,4,98.0,83.0,2075,15.9,77,usa,dodge colt m/m
237,30.5,4,98.0,63.0,2051,17.0,77,usa,chevrolet chevette
141,29.0,4,98.0,83.0,2219,16.5,74,europe,audi fox
266,30.0,4,98.0,68.0,2155,16.5,78,usa,chevrolet chevette
379,36.0,4,98.0,70.0,2125,17.3,82,usa,mercury lynx l
279,29.5,4,98.0,68.0,2135,16.6,78,japan,honda accord lx
295,35.7,4,98.0,80.0,1915,14.4,79,usa,dodge colt hatchback custom
309,41.5,4,98.0,76.0,2144,14.7,80,europe,vw rabbit
311,32.1,4,98.0,70.0,2120,15.5,80,usa,chevrolet chevette
83,28.0,4,98.0,80.0,2164,15.0,72,usa,dodge colt (sw)
352,29.9,4,98.0,65.0,2380,20.7,81,usa,ford escort 2h
351,34.4,4,98.0,65.0,2045,16.2,81,usa,ford escort 4w
186,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
378,38.0,4,105.0,63.0,2125,14.7,82,usa,plymouth horizon miser
375,36.0,4,105.0,74.0,1980,15.3,82,europe,volkswagen rabbit l
353,33.0,4,105.0,74.0,2190,14.2,81,europe,volkswagen jetta
350,34.7,4,105.0,63.0,2215,14.9,81,usa,plymouth horizon 4
302,34.5,4,105.0,70.0,2150,14.9,79,usa,plymouth horizon tc3
269,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
301,34.2,4,105.0,70.0,2200,13.2,79,usa,plymouth horizon
337,32.4,4,107.0,72.0,2290,17.0,80,japan,honda accord
381,36.0,4,107.0,75.0,2205,14.5,82,japan,honda accord
355,33.7,4,107.0,75.0,2210,14.4,81,japan,honda prelude
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
182,28.0,4,107.0,86.0,2464,15.5,76,europe,fiat 131
382,34.0,4,108.0,70.0,2245,16.9,82,japan,toyota corolla
150,26.0,4,108.0,93.0,2391,15.5,74,japan,subaru
110,22.0,4,108.0,94.0,2379,16.5,73,japan,datsun 610
321,32.2,4,108.0,75.0,2265,15.2,80,japan,toyota corolla
356,32.4,4,108.0,75.0,2350,16.8,81,japan,toyota corolla
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
217,30.0,4,111.0,80.0,2155,14.8,77,usa,buick opel isuzu deluxe
370,31.0,4,112.0,85.0,2575,16.2,82,usa,pontiac j2000 se hatchback
369,34.0,4,112.0,88.0,2395,18.0,82,usa,chevrolet cavalier 2-door
368,27.0,4,112.0,88.0,2640,18.6,82,usa,chevrolet cavalier wagon
367,28.0,4,112.0,88.0,2605,19.6,82,usa,chevrolet cavalier
57,24.0,4,113.0,95.0,2278,15.5,72,japan,toyota corona hardtop
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
119,20.0,4,114.0,91.0,2582,14.0,73,europe,audi 100ls
177,23.0,4,115.0,95.0,2694,15.0,75,europe,audi 100ls
148,26.0,4,116.0,75.0,2246,14.0,74,europe,fiat 124 tc
50,28.0,4,116.0,90.0,2123,14.0,71,europe,opel 1900
183,25.0,4,116.0,81.0,2220,16.9,76,europe,opel 1900
118,24.0,4,116.0,75.0,2158,15.5,73,europe,opel manta
357,32.9,4,119.0,100.0,2615,14.8,81,japan,datsun 200sx
273,23.9,4,119.0,97.0,2405,14.9,78,japan,datsun 200-sx
268,27.2,4,119.0,97.0,2300,14.7,78,japan,datsun 510
320,37.0,4,119.0,92.0,2434,15.0,80,japan,datsun 510 hatchback
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10
209,19.0,4,120.0,88.0,3270,21.9,76,europe,peugeot 504
178,23.0,4,120.0,88.0,2957,17.0,75,europe,peugeot 504
149,24.0,4,120.0,97.0,2489,15.0,74,japan,honda civic
82,23.0,4,120.0,97.0,2506,14.5,72,japan,toyouta corona mark ii (sw)
380,36.0,4,120.0,88.0,2160,14.5,82,japan,nissan stanza xe
78,21.0,4,120.0,87.0,2979,19.5,72,europe,peugeot 504 (sw)
319,31.3,4,120.0,75.0,2542,17.5,80,japan,mazda 626
358,31.6,4,120.0,74.0,2635,18.3,81,japan,mazda 626
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
242,21.5,4,121.0,110.0,2600,12.8,77,europe,bmw 320i
122,24.0,4,121.0,110.0,2660,14.0,73,europe,saab 99le
77,22.0,4,121.0,76.0,2511,18.0,72,europe,volkswagen 411 (sw)
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le
179,22.0,4,121.0,98.0,2945,14.5,75,europe,volvo 244dl
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
76,18.0,4,121.0,112.0,2933,14.5,72,europe,volvo 145e (sw)
276,21.6,4,121.0,115.0,2795,15.7,78,europe,saab 99gle
296,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
120,19.0,4,121.0,112.0,2868,15.5,73,europe,volvo 144ea
327,36.4,5,121.0,67.0,2950,19.9,80,europe,audi 5000s (diesel)
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
335,35.0,4,122.0,88.0,2500,15.1,80,europe,triumph tr7 coupe
61,21.0,4,122.0,86.0,2226,16.5,72,usa,ford pinto runabout
219,25.5,4,122.0,96.0,2300,15.5,77,usa,plymouth arrow gs
49,23.0,4,122.0,86.0,2220,14.0,71,usa,mercury capri 2000
207,20.0,4,130.0,102.0,3150,15.7,76,europe,volvo 245
274,20.3,5,131.0,103.0,2830,15.9,78,europe,audi 5000
267,27.5,4,134.0,95.0,2560,14.2,78,japan,toyota corona
318,29.8,4,134.0,90.0,2711,15.5,80,japan,toyota corona liftback
270,21.1,4,134.0,95.0,2515,14.8,78,japan,toyota celica gt liftback
171,24.0,4,134.0,96.0,2702,13.5,75,japan,toyota corona
371,29.0,4,135.0,84.0,2525,16.0,82,usa,dodge aries se
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
342,30.0,4,135.0,84.0,2385,12.9,81,usa,plymouth reliant
338,27.2,4,135.0,84.0,2490,15.7,81,usa,plymouth reliant
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
132,25.0,4,140.0,75.0,2542,17.0,74,usa,chevrolet vega
255,25.1,4,140.0,88.0,2720,15.4,78,usa,ford fairmont (man)
314,26.4,4,140.0,88.0,2870,18.1,80,usa,ford fairmont
184,25.0,4,140.0,92.0,2572,14.9,76,usa,capri ii
109,21.0,4,140.0,72.0,2401,19.5,73,usa,chevrolet vega
170,23.0,4,140.0,78.0,2592,18.5,75,usa,pontiac astro
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
46,22.0,4,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
282,22.3,4,140.0,88.0,2890,17.3,79,usa,ford fairmont 4
30,28.0,4,140.0,90.0,2264,15.5,71,usa,chevrolet vega 2300
373,24.0,4,140.0,92.0,2865,16.4,82,usa,ford fairmont futura
236,25.5,4,140.0,89.0,2755,15.8,77,usa,ford mustang ii 2+2
299,27.2,4,141.0,71.0,3190,24.8,79,europe,peugeot 504
359,28.1,4,141.0,80.0,3230,20.4,81,europe,peugeot 505s turbo diesel
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
360,30.7,6,145.0,76.0,3160,19.6,81,europe,volvo diesel
328,30.0,4,146.0,67.0,3250,21.8,80,europe,mercedes-benz 240d
362,24.2,6,146.0,120.0,2930,13.8,81,japan,datsun 810 maxima
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
315,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
313,28.0,4,151.0,90.0,2678,16.5,80,usa,chevrolet citation
372,27.0,4,151.0,90.0,2735,18.0,82,usa,pontiac phoenix
234,24.5,4,151.0,88.0,2740,16.0,77,usa,pontiac sunbird coupe
272,23.8,4,151.0,85.0,2855,17.6,78,usa,oldsmobile starfire sx
308,33.5,4,151.0,90.0,2556,13.2,79,usa,pontiac phoenix
339,26.6,4,151.0,84.0,2635,16.4,81,usa,buick skylark
305,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited
392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
113,21.0,6,155.0,107.0,2472,14.0,73,usa,mercury capri v6
271,23.2,4,156.0,105.0,2745,16.7,78,usa,plymouth sapporo
340,25.8,4,156.0,92.0,2620,14.4,81,usa,dodge aries wagon (sw)
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
323,27.9,4,156.0,105.0,2800,14.4,80,usa,dodge colt
388,26.0,4,156.0,92.0,2585,14.5,82,usa,chrysler lebaron medallion
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
275,17.0,6,163.0,125.0,3140,13.6,78,europe,volvo 264gl
277,16.2,6,163.0,133.0,3410,15.8,78,europe,peugeot 604sl
333,32.7,6,168.0,132.0,2910,11.4,80,japan,datsun 280-zx
361,25.4,6,168.0,116.0,2900,12.6,81,japan,toyota cressida
211,16.5,6,168.0,120.0,3820,16.7,76,europe,mercedes-benz 280s
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
341,23.5,6,173.0,110.0,2725,12.6,81,usa,chevrolet citation
306,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
307,26.8,6,173.0,115.0,2700,12.9,79,usa,oldsmobile omega brougham
386,25.0,6,181.0,110.0,2945,16.4,82,usa,buick century limited
297,25.4,5,183.0,77.0,3530,20.1,79,europe,mercedes benz 300d
101,23.0,6,198.0,95.0,2904,16.0,73,usa,plymouth duster
125,20.0,6,198.0,95.0,3102,16.5,74,usa,plymouth duster
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
259,20.8,6,200.0,85.0,3070,16.7,78,usa,mercury zephyr
254,20.2,6,200.0,85.0,2965,15.8,78,usa,ford fairmont (auto)
253,20.5,6,200.0,95.0,3155,18.2,78,usa,chevrolet malibu
193,24.0,6,200.0,81.0,3012,17.6,76,usa,ford maverick
365,20.2,6,200.0,88.0,3060,17.1,81,usa,ford granada gl
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
281,19.8,6,200.0,85.0,2990,18.2,79,usa,mercury zephyr 6
260,18.6,6,225.0,110.0,3620,18.7,78,usa,dodge aspen
227,19.0,6,225.0,100.0,3630,17.7,77,usa,plymouth volare custom
191,22.0,6,225.0,100.0,3233,15.4,76,usa,plymouth valiant
97,18.0,6,225.0,105.0,3121,16.5,73,usa,plymouth valiant
34,16.0,6,225.0,105.0,3439,15.5,71,usa,plymouth satellite custom
135,18.0,6,225.0,105.0,3613,16.5,74,usa,plymouth satellite sebring
152,19.0,6,225.0,95.0,3264,16.0,75,usa,plymouth valiant custom
366,17.6,6,225.0,85.0,3465,16.6,81,usa,chrysler lebaron salon
284,20.6,6,225.0,110.0,3360,16.6,79,usa,dodge aspen 6
256,20.5,6,225.0,100.0,3430,17.2,78,usa,plymouth volare
199,20.0,6,225.0,100.0,3651,17.7,76,usa,dodge aspen se
163,18.0,6,225.0,95.0,3785,19.0,75,usa,plymouth fury
316,19.1,6,225.0,90.0,3381,18.7,80,usa,dodge aspen
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
226,20.5,6,231.0,105.0,3425,16.9,77,usa,buick skylark
252,19.2,6,231.0,105.0,3535,19.2,78,usa,pontiac phoenix lj
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century
164,21.0,6,231.0,110.0,3039,15.0,75,usa,buick skyhawk
263,17.7,6,231.0,165.0,3445,13.4,78,usa,buick regal sport coupe (turbo)
363,22.4,6,231.0,110.0,3415,15.8,81,usa,buick century
258,20.6,6,231.0,105.0,3380,15.8,78,usa,buick century special
127,19.0,6,232.0,100.0,2901,16.0,74,usa,amc hornet
389,22.0,6,232.0,112.0,2835,14.7,82,usa,ford granada l
169,20.0,6,232.0,100.0,2914,16.0,75,usa,amc gremlin
176,19.0,6,232.0,90.0,3211,17.0,75,usa,amc pacer
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
283,20.2,6,232.0,90.0,3265,18.2,79,usa,amc concord dl 6
99,18.0,6,232.0,100.0,2945,16.0,73,usa,amc hornet
194,22.5,6,232.0,90.0,3085,17.6,76,usa,amc hornet
257,19.4,6,232.0,90.0,3210,17.2,78,usa,amc concord
107,18.0,6,232.0,100.0,2789,15.0,73,usa,amc gremlin
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch
155,15.0,6,250.0,72.0,3158,19.5,75,usa,ford maverick
133,16.0,6,250.0,100.0,3781,17.0,74,usa,chevrolet chevelle malibu classic
98,16.0,6,250.0,100.0,3278,18.0,73,usa,chevrolet nova custom
100,18.0,6,250.0,88.0,3021,16.5,73,usa,ford maverick
128,15.0,6,250.0,100.0,3336,17.0,74,usa,chevrolet nova
225,17.5,6,250.0,110.0,3520,16.4,77,usa,chevrolet concours
228,18.5,6,250.0,98.0,3525,19.0,77,usa,ford granada
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu
47,19.0,6,250.0,100.0,3282,15.0,71,usa,pontiac firebird
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
192,22.0,6,250.0,105.0,3353,14.5,76,usa,chevrolet nova
153,18.0,6,250.0,105.0,3459,16.0,75,usa,chevrolet nova
201,18.5,6,250.0,110.0,3645,16.2,76,usa,pontiac ventura sj
36,19.0,6,250.0,88.0,3302,15.5,71,usa,ford torino 500
45,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
162,15.0,6,258.0,110.0,3730,19.0,75,usa,amc matador
134,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
202,17.5,6,258.0,95.0,3193,17.8,76,usa,amc pacer d/l
261,18.1,6,258.0,120.0,3410,15.1,78,usa,amc concord d/l
222,17.0,8,260.0,110.0,4060,19.0,77,usa,oldsmobile cutlass supreme
300,23.9,8,260.0,90.0,3420,22.2,79,usa,oldsmobile cutlass salon brougham
249,19.9,8,260.0,110.0,3365,15.5,78,usa,oldsmobile cutlass salon brougham
165,20.0,8,262.0,110.0,3221,13.5,75,usa,chevrolet monza 2+2
387,38.0,6,262.0,85.0,3015,17.0,82,usa,oldsmobile cutlass ciera (diesel)
291,19.2,8,267.0,125.0,3605,15.0,79,usa,chevrolet malibu classic (sw)
251,20.2,8,302.0,139.0,3570,12.8,78,usa,mercury monarch ghia
214,13.0,8,302.0,130.0,3870,15.0,76,usa,ford f108
224,15.0,8,302.0,130.0,4295,14.9,77,usa,mercury cougar brougham
139,14.0,8,302.0,140.0,4638,16.0,74,usa,ford gran torino (sw)
88,14.0,8,302.0,137.0,4042,14.5,73,usa,ford gran torino
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
264,18.1,8,302.0,139.0,3205,11.2,78,usa,ford futura
136,16.0,8,302.0,140.0,4141,14.0,74,usa,ford gran torino
74,13.0,8,302.0,140.0,4294,16.0,72,usa,ford gran torino (sw)
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii
286,17.6,8,302.0,129.0,3725,13.4,79,usa,ford ltd landau
66,17.0,8,304.0,150.0,3672,11.5,72,usa,amc ambassador sst
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
189,15.5,8,304.0,120.0,3962,13.9,76,usa,amc matador
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
72,15.0,8,304.0,150.0,3892,12.5,72,usa,amc matador (sw)
140,14.0,8,304.0,150.0,4257,15.5,74,usa,amc matador (sw)
262,19.2,8,305.0,145.0,3425,13.2,78,usa,chevrolet monte carlo landau
187,17.5,8,305.0,140.0,4215,13.0,76,usa,chevrolet chevelle malibu classic
221,17.5,8,305.0,145.0,3880,12.5,77,usa,chevrolet caprice classic
285,17.0,8,305.0,130.0,3840,15.4,79,usa,chevrolet caprice classic
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
73,13.0,8,307.0,130.0,4098,14.0,72,usa,chevrolet chevelle concours (sw)
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
41,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
265,17.5,8,318.0,140.0,4080,13.7,78,usa,dodge magnum xe
223,15.5,8,318.0,145.0,4140,13.7,77,usa,dodge monaco brougham
250,19.4,8,318.0,140.0,3735,13.2,78,usa,dodge diplomat
75,14.0,8,318.0,150.0,4077,14.0,72,usa,plymouth satellite custom (sw)
288,18.2,8,318.0,135.0,3830,15.2,79,usa,dodge st. regis
215,13.0,8,318.0,150.0,3755,14.0,76,usa,dodge d100
208,13.0,8,318.0,150.0,3940,13.2,76,usa,plymouth volare premier v8
93,14.0,8,318.0,150.0,4237,14.5,73,usa,plymouth fury gran sedan
188,16.0,8,318.0,150.0,4190,13.0,76,usa,dodge coronet brougham
89,15.0,8,318.0,150.0,3777,12.5,73,usa,dodge coronet custom
121,15.0,8,318.0,150.0,3399,11.0,73,usa,dodge dart custom
158,16.0,8,318.0,150.0,4498,14.5,75,usa,plymouth grand fury
64,15.0,8,318.0,150.0,4135,13.5,72,usa,plymouth fury iii
138,14.0,8,318.0,150.0,4457,13.5,74,usa,dodge coronet custom (sw)
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
106,12.0,8,350.0,180.0,4499,12.5,73,usa,oldsmobile vista cruiser
157,15.0,8,350.0,145.0,4440,14.0,75,usa,chevrolet bel air
212,16.5,8,350.0,180.0,4380,12.1,76,usa,cadillac seville
213,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
124,11.0,8,350.0,180.0,3664,11.0,73,usa,oldsmobile omega
364,26.6,8,350.0,105.0,3725,19.0,81,usa,oldsmobile cutlass ls
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
62,13.0,8,350.0,165.0,4274,12.0,72,usa,chevrolet impala
230,15.5,8,350.0,170.0,4165,11.4,77,usa,chevrolet monte carlo landau
115,15.0,8,350.0,145.0,4082,13.0,73,usa,chevrolet monte carlo s
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
69,12.0,8,350.0,160.0,4456,13.5,72,usa,oldsmobile delta 88 royale
298,23.0,8,350.0,125.0,3900,17.4,79,usa,cadillac eldorado
68,13.0,8,350.0,155.0,4502,13.5,72,usa,buick lesabre custom

In [ ]:
car.sort_values('displacement', ascending = False)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
94,13.0,8,440.0,215.0,4735,11.0,73,usa,chrysler new yorker brougham
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
63,14.0,8,400.0,175.0,4385,12.0,72,usa,pontiac catalina
229,16.0,8,400.0,180.0,4220,11.1,77,usa,pontiac grand prix lj
104,12.0,8,400.0,167.0,4906,12.5,73,usa,ford country
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
116,16.0,8,400.0,230.0,4278,9.5,73,usa,pontiac grand prix
39,14.0,8,400.0,175.0,4464,11.5,71,usa,pontiac catalina brougham
43,13.0,8,400.0,170.0,4746,12.0,71,usa,ford country squire (sw)
231,15.5,8,400.0,190.0,4325,12.2,77,usa,chrysler cordoba
70,13.0,8,400.0,190.0,4422,12.5,72,usa,chrysler newport royal
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
156,16.0,8,400.0,170.0,4668,11.5,75,usa,pontiac catalina
91,13.0,8,400.0,150.0,4464,12.0,73,usa,chevrolet caprice classic
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
105,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
292,18.5,8,360.0,150.0,3940,13.0,79,usa,chrysler lebaron town @ country (sw)
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
96,13.0,8,360.0,175.0,3821,11.0,73,usa,amc ambassador brougham
290,15.5,8,351.0,142.0,4054,14.3,79,usa,ford country squire (sw)
190,14.5,8,351.0,152.0,4215,12.8,76,usa,ford gran torino
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
287,16.5,8,351.0,138.0,3955,13.2,79,usa,mercury grand marquis
65,14.0,8,351.0,153.0,4129,13.0,72,usa,ford galaxie 500
232,16.0,8,351.0,149.0,4335,14.5,77,usa,ford thunderbird
92,13.0,8,351.0,158.0,4363,13.0,73,usa,ford ltd
159,14.0,8,351.0,148.0,4657,13.5,75,usa,ford ltd
364,26.6,8,350.0,105.0,3725,19.0,81,usa,oldsmobile cutlass ls
106,12.0,8,350.0,180.0,4499,12.5,73,usa,oldsmobile vista cruiser
115,15.0,8,350.0,145.0,4082,13.0,73,usa,chevrolet monte carlo s
62,13.0,8,350.0,165.0,4274,12.0,72,usa,chevrolet impala
157,15.0,8,350.0,145.0,4440,14.0,75,usa,chevrolet bel air
124,11.0,8,350.0,180.0,3664,11.0,73,usa,oldsmobile omega
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
68,13.0,8,350.0,155.0,4502,13.5,72,usa,buick lesabre custom
69,12.0,8,350.0,160.0,4456,13.5,72,usa,oldsmobile delta 88 royale
87,13.0,8,350.0,145.0,3988,13.0,73,usa,chevrolet malibu
289,16.9,8,350.0,155.0,4360,14.9,79,usa,buick estate wagon (sw)
38,14.0,8,350.0,165.0,4209,12.0,71,usa,chevrolet impala
298,23.0,8,350.0,125.0,3900,17.4,79,usa,cadillac eldorado
230,15.5,8,350.0,170.0,4165,11.4,77,usa,chevrolet monte carlo landau
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
213,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
212,16.5,8,350.0,180.0,4380,12.1,76,usa,cadillac seville
85,13.0,8,350.0,175.0,4100,13.0,73,usa,buick century 350
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
75,14.0,8,318.0,150.0,4077,14.0,72,usa,plymouth satellite custom (sw)
265,17.5,8,318.0,140.0,4080,13.7,78,usa,dodge magnum xe
250,19.4,8,318.0,140.0,3735,13.2,78,usa,dodge diplomat
93,14.0,8,318.0,150.0,4237,14.5,73,usa,plymouth fury gran sedan
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
223,15.5,8,318.0,145.0,4140,13.7,77,usa,dodge monaco brougham
215,13.0,8,318.0,150.0,3755,14.0,76,usa,dodge d100
89,15.0,8,318.0,150.0,3777,12.5,73,usa,dodge coronet custom
158,16.0,8,318.0,150.0,4498,14.5,75,usa,plymouth grand fury
64,15.0,8,318.0,150.0,4135,13.5,72,usa,plymouth fury iii
208,13.0,8,318.0,150.0,3940,13.2,76,usa,plymouth volare premier v8
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
288,18.2,8,318.0,135.0,3830,15.2,79,usa,dodge st. regis
188,16.0,8,318.0,150.0,4190,13.0,76,usa,dodge coronet brougham
121,15.0,8,318.0,150.0,3399,11.0,73,usa,dodge dart custom
41,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
138,14.0,8,318.0,150.0,4457,13.5,74,usa,dodge coronet custom (sw)
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
73,13.0,8,307.0,130.0,4098,14.0,72,usa,chevrolet chevelle concours (sw)
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
221,17.5,8,305.0,145.0,3880,12.5,77,usa,chevrolet caprice classic
285,17.0,8,305.0,130.0,3840,15.4,79,usa,chevrolet caprice classic
187,17.5,8,305.0,140.0,4215,13.0,76,usa,chevrolet chevelle malibu classic
262,19.2,8,305.0,145.0,3425,13.2,78,usa,chevrolet monte carlo landau
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
189,15.5,8,304.0,120.0,3962,13.9,76,usa,amc matador
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador
66,17.0,8,304.0,150.0,3672,11.5,72,usa,amc ambassador sst
72,15.0,8,304.0,150.0,3892,12.5,72,usa,amc matador (sw)
140,14.0,8,304.0,150.0,4257,15.5,74,usa,amc matador (sw)
74,13.0,8,302.0,140.0,4294,16.0,72,usa,ford gran torino (sw)
251,20.2,8,302.0,139.0,3570,12.8,78,usa,mercury monarch ghia
136,16.0,8,302.0,140.0,4141,14.0,74,usa,ford gran torino
224,15.0,8,302.0,130.0,4295,14.9,77,usa,mercury cougar brougham
286,17.6,8,302.0,129.0,3725,13.4,79,usa,ford ltd landau
264,18.1,8,302.0,139.0,3205,11.2,78,usa,ford futura
88,14.0,8,302.0,137.0,4042,14.5,73,usa,ford gran torino
214,13.0,8,302.0,130.0,3870,15.0,76,usa,ford f108
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii
139,14.0,8,302.0,140.0,4638,16.0,74,usa,ford gran torino (sw)
291,19.2,8,267.0,125.0,3605,15.0,79,usa,chevrolet malibu classic (sw)
387,38.0,6,262.0,85.0,3015,17.0,82,usa,oldsmobile cutlass ciera (diesel)
165,20.0,8,262.0,110.0,3221,13.5,75,usa,chevrolet monza 2+2
300,23.9,8,260.0,90.0,3420,22.2,79,usa,oldsmobile cutlass salon brougham
222,17.0,8,260.0,110.0,4060,19.0,77,usa,oldsmobile cutlass supreme
249,19.9,8,260.0,110.0,3365,15.5,78,usa,oldsmobile cutlass salon brougham
134,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
261,18.1,6,258.0,120.0,3410,15.1,78,usa,amc concord d/l
202,17.5,6,258.0,95.0,3193,17.8,76,usa,amc pacer d/l
45,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
162,15.0,6,258.0,110.0,3730,19.0,75,usa,amc matador
128,15.0,6,250.0,100.0,3336,17.0,74,usa,chevrolet nova
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu
133,16.0,6,250.0,100.0,3781,17.0,74,usa,chevrolet chevelle malibu classic
47,19.0,6,250.0,100.0,3282,15.0,71,usa,pontiac firebird
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
225,17.5,6,250.0,110.0,3520,16.4,77,usa,chevrolet concours
155,15.0,6,250.0,72.0,3158,19.5,75,usa,ford maverick
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch
153,18.0,6,250.0,105.0,3459,16.0,75,usa,chevrolet nova
228,18.5,6,250.0,98.0,3525,19.0,77,usa,ford granada
36,19.0,6,250.0,88.0,3302,15.5,71,usa,ford torino 500
201,18.5,6,250.0,110.0,3645,16.2,76,usa,pontiac ventura sj
100,18.0,6,250.0,88.0,3021,16.5,73,usa,ford maverick
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
98,16.0,6,250.0,100.0,3278,18.0,73,usa,chevrolet nova custom
192,22.0,6,250.0,105.0,3353,14.5,76,usa,chevrolet nova
389,22.0,6,232.0,112.0,2835,14.7,82,usa,ford granada l
257,19.4,6,232.0,90.0,3210,17.2,78,usa,amc concord
99,18.0,6,232.0,100.0,2945,16.0,73,usa,amc hornet
283,20.2,6,232.0,90.0,3265,18.2,79,usa,amc concord dl 6
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
176,19.0,6,232.0,90.0,3211,17.0,75,usa,amc pacer
107,18.0,6,232.0,100.0,2789,15.0,73,usa,amc gremlin
169,20.0,6,232.0,100.0,2914,16.0,75,usa,amc gremlin
127,19.0,6,232.0,100.0,2901,16.0,74,usa,amc hornet
194,22.5,6,232.0,90.0,3085,17.6,76,usa,amc hornet
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador
164,21.0,6,231.0,110.0,3039,15.0,75,usa,buick skyhawk
363,22.4,6,231.0,110.0,3415,15.8,81,usa,buick century
252,19.2,6,231.0,105.0,3535,19.2,78,usa,pontiac phoenix lj
258,20.6,6,231.0,105.0,3380,15.8,78,usa,buick century special
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century
263,17.7,6,231.0,165.0,3445,13.4,78,usa,buick regal sport coupe (turbo)
226,20.5,6,231.0,105.0,3425,16.9,77,usa,buick skylark
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
163,18.0,6,225.0,95.0,3785,19.0,75,usa,plymouth fury
191,22.0,6,225.0,100.0,3233,15.4,76,usa,plymouth valiant
256,20.5,6,225.0,100.0,3430,17.2,78,usa,plymouth volare
199,20.0,6,225.0,100.0,3651,17.7,76,usa,dodge aspen se
97,18.0,6,225.0,105.0,3121,16.5,73,usa,plymouth valiant
260,18.6,6,225.0,110.0,3620,18.7,78,usa,dodge aspen
135,18.0,6,225.0,105.0,3613,16.5,74,usa,plymouth satellite sebring
152,19.0,6,225.0,95.0,3264,16.0,75,usa,plymouth valiant custom
284,20.6,6,225.0,110.0,3360,16.6,79,usa,dodge aspen 6
227,19.0,6,225.0,100.0,3630,17.7,77,usa,plymouth volare custom
316,19.1,6,225.0,90.0,3381,18.7,80,usa,dodge aspen
366,17.6,6,225.0,85.0,3465,16.6,81,usa,chrysler lebaron salon
34,16.0,6,225.0,105.0,3439,15.5,71,usa,plymouth satellite custom
281,19.8,6,200.0,85.0,2990,18.2,79,usa,mercury zephyr 6
254,20.2,6,200.0,85.0,2965,15.8,78,usa,ford fairmont (auto)
253,20.5,6,200.0,95.0,3155,18.2,78,usa,chevrolet malibu
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
193,24.0,6,200.0,81.0,3012,17.6,76,usa,ford maverick
365,20.2,6,200.0,88.0,3060,17.1,81,usa,ford granada gl
259,20.8,6,200.0,85.0,3070,16.7,78,usa,mercury zephyr
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
125,20.0,6,198.0,95.0,3102,16.5,74,usa,plymouth duster
101,23.0,6,198.0,95.0,2904,16.0,73,usa,plymouth duster
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
297,25.4,5,183.0,77.0,3530,20.1,79,europe,mercedes benz 300d
386,25.0,6,181.0,110.0,2945,16.4,82,usa,buick century limited
306,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
341,23.5,6,173.0,110.0,2725,12.6,81,usa,chevrolet citation
307,26.8,6,173.0,115.0,2700,12.9,79,usa,oldsmobile omega brougham
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
361,25.4,6,168.0,116.0,2900,12.6,81,japan,toyota cressida
333,32.7,6,168.0,132.0,2910,11.4,80,japan,datsun 280-zx
211,16.5,6,168.0,120.0,3820,16.7,76,europe,mercedes-benz 280s
275,17.0,6,163.0,125.0,3140,13.6,78,europe,volvo 264gl
277,16.2,6,163.0,133.0,3410,15.8,78,europe,peugeot 604sl
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
388,26.0,4,156.0,92.0,2585,14.5,82,usa,chrysler lebaron medallion
323,27.9,4,156.0,105.0,2800,14.4,80,usa,dodge colt
340,25.8,4,156.0,92.0,2620,14.4,81,usa,dodge aries wagon (sw)
271,23.2,4,156.0,105.0,2745,16.7,78,usa,plymouth sapporo
113,21.0,6,155.0,107.0,2472,14.0,73,usa,mercury capri v6
372,27.0,4,151.0,90.0,2735,18.0,82,usa,pontiac phoenix
339,26.6,4,151.0,84.0,2635,16.4,81,usa,buick skylark
234,24.5,4,151.0,88.0,2740,16.0,77,usa,pontiac sunbird coupe
272,23.8,4,151.0,85.0,2855,17.6,78,usa,oldsmobile starfire sx
392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
315,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
313,28.0,4,151.0,90.0,2678,16.5,80,usa,chevrolet citation
308,33.5,4,151.0,90.0,2556,13.2,79,usa,pontiac phoenix
305,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
328,30.0,4,146.0,67.0,3250,21.8,80,europe,mercedes-benz 240d
362,24.2,6,146.0,120.0,2930,13.8,81,japan,datsun 810 maxima
360,30.7,6,145.0,76.0,3160,19.6,81,europe,volvo diesel
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
359,28.1,4,141.0,80.0,3230,20.4,81,europe,peugeot 505s turbo diesel
299,27.2,4,141.0,71.0,3190,24.8,79,europe,peugeot 504
30,28.0,4,140.0,90.0,2264,15.5,71,usa,chevrolet vega 2300
170,23.0,4,140.0,78.0,2592,18.5,75,usa,pontiac astro
255,25.1,4,140.0,88.0,2720,15.4,78,usa,ford fairmont (man)
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
109,21.0,4,140.0,72.0,2401,19.5,73,usa,chevrolet vega
373,24.0,4,140.0,92.0,2865,16.4,82,usa,ford fairmont futura
236,25.5,4,140.0,89.0,2755,15.8,77,usa,ford mustang ii 2+2
184,25.0,4,140.0,92.0,2572,14.9,76,usa,capri ii
314,26.4,4,140.0,88.0,2870,18.1,80,usa,ford fairmont
46,22.0,4,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
132,25.0,4,140.0,75.0,2542,17.0,74,usa,chevrolet vega
282,22.3,4,140.0,88.0,2890,17.3,79,usa,ford fairmont 4
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
342,30.0,4,135.0,84.0,2385,12.9,81,usa,plymouth reliant
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
338,27.2,4,135.0,84.0,2490,15.7,81,usa,plymouth reliant
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
371,29.0,4,135.0,84.0,2525,16.0,82,usa,dodge aries se
318,29.8,4,134.0,90.0,2711,15.5,80,japan,toyota corona liftback
270,21.1,4,134.0,95.0,2515,14.8,78,japan,toyota celica gt liftback
267,27.5,4,134.0,95.0,2560,14.2,78,japan,toyota corona
171,24.0,4,134.0,96.0,2702,13.5,75,japan,toyota corona
274,20.3,5,131.0,103.0,2830,15.9,78,europe,audi 5000
207,20.0,4,130.0,102.0,3150,15.7,76,europe,volvo 245
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
61,21.0,4,122.0,86.0,2226,16.5,72,usa,ford pinto runabout
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
335,35.0,4,122.0,88.0,2500,15.1,80,europe,triumph tr7 coupe
219,25.5,4,122.0,96.0,2300,15.5,77,usa,plymouth arrow gs
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
49,23.0,4,122.0,86.0,2220,14.0,71,usa,mercury capri 2000
122,24.0,4,121.0,110.0,2660,14.0,73,europe,saab 99le
179,22.0,4,121.0,98.0,2945,14.5,75,europe,volvo 244dl
296,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
77,22.0,4,121.0,76.0,2511,18.0,72,europe,volkswagen 411 (sw)
76,18.0,4,121.0,112.0,2933,14.5,72,europe,volvo 145e (sw)
327,36.4,5,121.0,67.0,2950,19.9,80,europe,audi 5000s (diesel)
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
276,21.6,4,121.0,115.0,2795,15.7,78,europe,saab 99gle
242,21.5,4,121.0,110.0,2600,12.8,77,europe,bmw 320i
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le
120,19.0,4,121.0,112.0,2868,15.5,73,europe,volvo 144ea
319,31.3,4,120.0,75.0,2542,17.5,80,japan,mazda 626
149,24.0,4,120.0,97.0,2489,15.0,74,japan,honda civic
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
178,23.0,4,120.0,88.0,2957,17.0,75,europe,peugeot 504
380,36.0,4,120.0,88.0,2160,14.5,82,japan,nissan stanza xe
78,21.0,4,120.0,87.0,2979,19.5,72,europe,peugeot 504 (sw)
82,23.0,4,120.0,97.0,2506,14.5,72,japan,toyouta corona mark ii (sw)
358,31.6,4,120.0,74.0,2635,18.3,81,japan,mazda 626
209,19.0,4,120.0,88.0,3270,21.9,76,europe,peugeot 504
273,23.9,4,119.0,97.0,2405,14.9,78,japan,datsun 200-sx
357,32.9,4,119.0,100.0,2615,14.8,81,japan,datsun 200sx
320,37.0,4,119.0,92.0,2434,15.0,80,japan,datsun 510 hatchback
268,27.2,4,119.0,97.0,2300,14.7,78,japan,datsun 510
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710
183,25.0,4,116.0,81.0,2220,16.9,76,europe,opel 1900
148,26.0,4,116.0,75.0,2246,14.0,74,europe,fiat 124 tc
50,28.0,4,116.0,90.0,2123,14.0,71,europe,opel 1900
118,24.0,4,116.0,75.0,2158,15.5,73,europe,opel manta
177,23.0,4,115.0,95.0,2694,15.0,75,europe,audi 100ls
119,20.0,4,114.0,91.0,2582,14.0,73,europe,audi 100ls
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
57,24.0,4,113.0,95.0,2278,15.5,72,japan,toyota corona hardtop
370,31.0,4,112.0,85.0,2575,16.2,82,usa,pontiac j2000 se hatchback
369,34.0,4,112.0,88.0,2395,18.0,82,usa,chevrolet cavalier 2-door
368,27.0,4,112.0,88.0,2640,18.6,82,usa,chevrolet cavalier wagon
367,28.0,4,112.0,88.0,2605,19.6,82,usa,chevrolet cavalier
217,30.0,4,111.0,80.0,2155,14.8,77,usa,buick opel isuzu deluxe
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
150,26.0,4,108.0,93.0,2391,15.5,74,japan,subaru
321,32.2,4,108.0,75.0,2265,15.2,80,japan,toyota corolla
110,22.0,4,108.0,94.0,2379,16.5,73,japan,datsun 610
356,32.4,4,108.0,75.0,2350,16.8,81,japan,toyota corolla
382,34.0,4,108.0,70.0,2245,16.9,82,japan,toyota corolla
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
381,36.0,4,107.0,75.0,2205,14.5,82,japan,honda accord
182,28.0,4,107.0,86.0,2464,15.5,76,europe,fiat 131
355,33.7,4,107.0,75.0,2210,14.4,81,japan,honda prelude
337,32.4,4,107.0,72.0,2290,17.0,80,japan,honda accord
375,36.0,4,105.0,74.0,1980,15.3,82,europe,volkswagen rabbit l
302,34.5,4,105.0,70.0,2150,14.9,79,usa,plymouth horizon tc3
301,34.2,4,105.0,70.0,2200,13.2,79,usa,plymouth horizon
350,34.7,4,105.0,63.0,2215,14.9,81,usa,plymouth horizon 4
378,38.0,4,105.0,63.0,2125,14.7,82,usa,plymouth horizon miser
353,33.0,4,105.0,74.0,2190,14.2,81,europe,volkswagen jetta
269,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
186,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
141,29.0,4,98.0,83.0,2219,16.5,74,europe,audi fox
311,32.1,4,98.0,70.0,2120,15.5,80,usa,chevrolet chevette
83,28.0,4,98.0,80.0,2164,15.0,72,usa,dodge colt (sw)
309,41.5,4,98.0,76.0,2144,14.7,80,europe,vw rabbit
114,26.0,4,98.0,90.0,2265,15.5,73,europe,fiat 124 sport coupe
352,29.9,4,98.0,65.0,2380,20.7,81,usa,ford escort 2h
351,34.4,4,98.0,65.0,2045,16.2,81,usa,ford escort 4w
379,36.0,4,98.0,70.0,2125,17.3,82,usa,mercury lynx l
196,24.5,4,98.0,60.0,2164,22.1,76,usa,chevrolet woody
266,30.0,4,98.0,68.0,2155,16.5,78,usa,chevrolet chevette
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
295,35.7,4,98.0,80.0,1915,14.4,79,usa,dodge colt hatchback custom
279,29.5,4,98.0,68.0,2135,16.6,78,japan,honda accord lx
185,26.0,4,98.0,79.0,2255,17.7,76,usa,dodge colt
216,31.5,4,98.0,68.0,2045,18.5,77,japan,honda accord cvcc
237,30.5,4,98.0,63.0,2051,17.0,77,usa,chevrolet chevette
238,33.5,4,98.0,83.0,2075,15.9,77,usa,dodge colt m/m
58,25.0,4,97.5,80.0,2126,17.0,72,usa,dodge colt hardtop
102,26.0,4,97.0,46.0,1950,21.0,73,europe,volkswagen super beetle
233,29.0,4,97.0,78.0,1940,14.5,77,europe,volkswagen rabbit custom
84,27.0,4,97.0,88.0,2100,16.5,72,japan,toyota corolla 1600 (sw)
235,26.0,4,97.0,75.0,2265,18.2,77,japan,toyota corolla liftback
167,29.0,4,97.0,75.0,2171,16.0,75,japan,toyota corolla
239,30.0,4,97.0,67.0,1985,16.4,77,japan,subaru dl
331,33.8,4,97.0,67.0,2145,18.0,80,japan,subaru dl
240,30.5,4,97.0,78.0,2190,14.1,77,europe,volkswagen dasher
108,20.0,4,97.0,88.0,2279,19.0,73,japan,toyota carina
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
346,32.3,4,97.0,67.0,2065,17.8,81,japan,subaru
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
81,28.0,4,97.0,92.0,2288,17.0,72,japan,datsun 510 (sw)
205,28.0,4,97.0,75.0,2155,16.4,76,japan,toyota corolla
203,29.5,4,97.0,71.0,1825,12.2,76,europe,volkswagen rabbit
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
143,26.0,4,97.0,78.0,2300,14.5,74,europe,opel manta
317,34.3,4,97.0,78.0,2188,15.8,80,europe,audi 4000
55,27.0,4,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
79,26.0,4,96.0,69.0,2189,18.0,72,europe,renault 12 (sw)
349,34.1,4,91.0,68.0,1985,16.0,81,japan,mazda glc 4
56,26.0,4,91.0,70.0,1955,20.5,71,usa,plymouth cricket
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
376,37.0,4,91.0,68.0,2025,18.2,82,japan,mazda glc custom l
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
377,31.0,4,91.0,68.0,1970,17.6,82,japan,mazda glc custom
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
198,33.0,4,91.0,53.0,1795,17.4,76,japan,honda civic
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc

In [ ]:
car.sort_values(['displacement', 'weight'], ascending = False)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
95,12.0,8,455.0,225.0,4951,11.0,73,usa,buick electra 225 custom
8,14.0,8,455.0,225.0,4425,10.0,70,usa,pontiac catalina
13,14.0,8,455.0,225.0,3086,10.0,70,usa,buick estate wagon (sw)
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala
94,13.0,8,440.0,215.0,4735,11.0,73,usa,chrysler new yorker brougham
7,14.0,8,440.0,215.0,4312,8.5,70,usa,plymouth fury iii
90,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
67,11.0,8,429.0,208.0,4633,11.0,72,usa,mercury marquis
5,15.0,8,429.0,198.0,4341,10.0,70,usa,ford galaxie 500
44,13.0,8,400.0,175.0,5140,12.0,71,usa,pontiac safari (sw)
103,11.0,8,400.0,150.0,4997,14.0,73,usa,chevrolet impala
104,12.0,8,400.0,167.0,4906,12.5,73,usa,ford country
43,13.0,8,400.0,170.0,4746,12.0,71,usa,ford country squire (sw)
156,16.0,8,400.0,170.0,4668,11.5,75,usa,pontiac catalina
39,14.0,8,400.0,175.0,4464,11.5,71,usa,pontiac catalina brougham
91,13.0,8,400.0,150.0,4464,12.0,73,usa,chevrolet caprice classic
70,13.0,8,400.0,190.0,4422,12.5,72,usa,chrysler newport royal
63,14.0,8,400.0,175.0,4385,12.0,72,usa,pontiac catalina
231,15.5,8,400.0,190.0,4325,12.2,77,usa,chrysler cordoba
116,16.0,8,400.0,230.0,4278,9.5,73,usa,pontiac grand prix
229,16.0,8,400.0,180.0,4220,11.1,77,usa,pontiac grand prix lj
12,15.0,8,400.0,150.0,3761,9.5,70,usa,chevrolet monte carlo
9,15.0,8,390.0,190.0,3850,8.5,70,usa,amc ambassador dpl
42,12.0,8,383.0,180.0,4955,11.5,71,usa,dodge monaco (sw)
10,15.0,8,383.0,170.0,3563,10.0,70,usa,dodge challenger se
105,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
25,10.0,8,360.0,215.0,4615,14.0,70,usa,ford f250
292,18.5,8,360.0,150.0,3940,13.0,79,usa,chrysler lebaron town @ country (sw)
96,13.0,8,360.0,175.0,3821,11.0,73,usa,amc ambassador brougham
159,14.0,8,351.0,148.0,4657,13.5,75,usa,ford ltd
92,13.0,8,351.0,158.0,4363,13.0,73,usa,ford ltd
232,16.0,8,351.0,149.0,4335,14.5,77,usa,ford thunderbird
190,14.5,8,351.0,152.0,4215,12.8,76,usa,ford gran torino
40,14.0,8,351.0,153.0,4154,13.5,71,usa,ford galaxie 500
65,14.0,8,351.0,153.0,4129,13.0,72,usa,ford galaxie 500
290,15.5,8,351.0,142.0,4054,14.3,79,usa,ford country squire (sw)
287,16.5,8,351.0,138.0,3955,13.2,79,usa,mercury grand marquis
137,13.0,8,350.0,150.0,4699,14.5,74,usa,buick century luxus (sw)
68,13.0,8,350.0,155.0,4502,13.5,72,usa,buick lesabre custom
106,12.0,8,350.0,180.0,4499,12.5,73,usa,oldsmobile vista cruiser
69,12.0,8,350.0,160.0,4456,13.5,72,usa,oldsmobile delta 88 royale
157,15.0,8,350.0,145.0,4440,14.0,75,usa,chevrolet bel air
212,16.5,8,350.0,180.0,4380,12.1,76,usa,cadillac seville
289,16.9,8,350.0,155.0,4360,14.9,79,usa,buick estate wagon (sw)
62,13.0,8,350.0,165.0,4274,12.0,72,usa,chevrolet impala
38,14.0,8,350.0,165.0,4209,12.0,71,usa,chevrolet impala
230,15.5,8,350.0,170.0,4165,11.4,77,usa,chevrolet monte carlo landau
85,13.0,8,350.0,175.0,4100,13.0,73,usa,buick century 350
115,15.0,8,350.0,145.0,4082,13.0,73,usa,chevrolet monte carlo s
213,13.0,8,350.0,145.0,4055,12.0,76,usa,chevy c10
87,13.0,8,350.0,145.0,3988,13.0,73,usa,chevrolet malibu
298,23.0,8,350.0,125.0,3900,17.4,79,usa,cadillac eldorado
364,26.6,8,350.0,105.0,3725,19.0,81,usa,oldsmobile cutlass ls
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
124,11.0,8,350.0,180.0,3664,11.0,73,usa,oldsmobile omega
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
158,16.0,8,318.0,150.0,4498,14.5,75,usa,plymouth grand fury
138,14.0,8,318.0,150.0,4457,13.5,74,usa,dodge coronet custom (sw)
27,11.0,8,318.0,210.0,4382,13.5,70,usa,dodge d200
93,14.0,8,318.0,150.0,4237,14.5,73,usa,plymouth fury gran sedan
188,16.0,8,318.0,150.0,4190,13.0,76,usa,dodge coronet brougham
223,15.5,8,318.0,145.0,4140,13.7,77,usa,dodge monaco brougham
64,15.0,8,318.0,150.0,4135,13.5,72,usa,plymouth fury iii
41,14.0,8,318.0,150.0,4096,13.0,71,usa,plymouth fury iii
265,17.5,8,318.0,140.0,4080,13.7,78,usa,dodge magnum xe
75,14.0,8,318.0,150.0,4077,14.0,72,usa,plymouth satellite custom (sw)
208,13.0,8,318.0,150.0,3940,13.2,76,usa,plymouth volare premier v8
288,18.2,8,318.0,135.0,3830,15.2,79,usa,dodge st. regis
89,15.0,8,318.0,150.0,3777,12.5,73,usa,dodge coronet custom
215,13.0,8,318.0,150.0,3755,14.0,76,usa,dodge d100
250,19.4,8,318.0,140.0,3735,13.2,78,usa,dodge diplomat
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
121,15.0,8,318.0,150.0,3399,11.0,73,usa,dodge dart custom
26,10.0,8,307.0,200.0,4376,15.0,70,usa,chevy c20
73,13.0,8,307.0,130.0,4098,14.0,72,usa,chevrolet chevelle concours (sw)
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
187,17.5,8,305.0,140.0,4215,13.0,76,usa,chevrolet chevelle malibu classic
221,17.5,8,305.0,145.0,3880,12.5,77,usa,chevrolet caprice classic
285,17.0,8,305.0,130.0,3840,15.4,79,usa,chevrolet caprice classic
262,19.2,8,305.0,145.0,3425,13.2,78,usa,chevrolet monte carlo landau
28,9.0,8,304.0,193.0,4732,18.5,70,usa,hi 1200d
140,14.0,8,304.0,150.0,4257,15.5,74,usa,amc matador (sw)
189,15.5,8,304.0,120.0,3962,13.9,76,usa,amc matador
72,15.0,8,304.0,150.0,3892,12.5,72,usa,amc matador (sw)
66,17.0,8,304.0,150.0,3672,11.5,72,usa,amc ambassador sst
86,14.0,8,304.0,150.0,3672,11.5,73,usa,amc matador
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
139,14.0,8,302.0,140.0,4638,16.0,74,usa,ford gran torino (sw)
224,15.0,8,302.0,130.0,4295,14.9,77,usa,mercury cougar brougham
74,13.0,8,302.0,140.0,4294,16.0,72,usa,ford gran torino (sw)
136,16.0,8,302.0,140.0,4141,14.0,74,usa,ford gran torino
88,14.0,8,302.0,137.0,4042,14.5,73,usa,ford gran torino
214,13.0,8,302.0,130.0,3870,15.0,76,usa,ford f108
286,17.6,8,302.0,129.0,3725,13.4,79,usa,ford ltd landau
251,20.2,8,302.0,139.0,3570,12.8,78,usa,mercury monarch ghia
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
264,18.1,8,302.0,139.0,3205,11.2,78,usa,ford futura
166,13.0,8,302.0,129.0,3169,12.0,75,usa,ford mustang ii
291,19.2,8,267.0,125.0,3605,15.0,79,usa,chevrolet malibu classic (sw)
165,20.0,8,262.0,110.0,3221,13.5,75,usa,chevrolet monza 2+2
387,38.0,6,262.0,85.0,3015,17.0,82,usa,oldsmobile cutlass ciera (diesel)
222,17.0,8,260.0,110.0,4060,19.0,77,usa,oldsmobile cutlass supreme
300,23.9,8,260.0,90.0,3420,22.2,79,usa,oldsmobile cutlass salon brougham
249,19.9,8,260.0,110.0,3365,15.5,78,usa,oldsmobile cutlass salon brougham
162,15.0,6,258.0,110.0,3730,19.0,75,usa,amc matador
134,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
261,18.1,6,258.0,120.0,3410,15.1,78,usa,amc concord d/l
202,17.5,6,258.0,95.0,3193,17.8,76,usa,amc pacer d/l
45,18.0,6,258.0,110.0,2962,13.5,71,usa,amc hornet sportabout (sw)
161,16.0,6,250.0,105.0,3897,18.5,75,usa,chevroelt chevelle malibu
133,16.0,6,250.0,100.0,3781,17.0,74,usa,chevrolet chevelle malibu classic
201,18.5,6,250.0,110.0,3645,16.2,76,usa,pontiac ventura sj
200,18.0,6,250.0,78.0,3574,21.0,76,usa,ford granada ghia
228,18.5,6,250.0,98.0,3525,19.0,77,usa,ford granada
225,17.5,6,250.0,110.0,3520,16.4,77,usa,chevrolet concours
153,18.0,6,250.0,105.0,3459,16.0,75,usa,chevrolet nova
154,15.0,6,250.0,72.0,3432,21.0,75,usa,mercury monarch
192,22.0,6,250.0,105.0,3353,14.5,76,usa,chevrolet nova
128,15.0,6,250.0,100.0,3336,17.0,74,usa,chevrolet nova
35,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
36,19.0,6,250.0,88.0,3302,15.5,71,usa,ford torino 500
47,19.0,6,250.0,100.0,3282,15.0,71,usa,pontiac firebird
98,16.0,6,250.0,100.0,3278,18.0,73,usa,chevrolet nova custom
155,15.0,6,250.0,72.0,3158,19.5,75,usa,ford maverick
48,18.0,6,250.0,88.0,3139,14.5,71,usa,ford mustang
100,18.0,6,250.0,88.0,3021,16.5,73,usa,ford maverick
37,18.0,6,232.0,100.0,3288,15.5,71,usa,amc matador
283,20.2,6,232.0,90.0,3265,18.2,79,usa,amc concord dl 6
176,19.0,6,232.0,90.0,3211,17.0,75,usa,amc pacer
257,19.4,6,232.0,90.0,3210,17.2,78,usa,amc concord
194,22.5,6,232.0,90.0,3085,17.6,76,usa,amc hornet
99,18.0,6,232.0,100.0,2945,16.0,73,usa,amc hornet
169,20.0,6,232.0,100.0,2914,16.0,75,usa,amc gremlin
127,19.0,6,232.0,100.0,2901,16.0,74,usa,amc hornet
389,22.0,6,232.0,112.0,2835,14.7,82,usa,ford granada l
107,18.0,6,232.0,100.0,2789,15.0,73,usa,amc gremlin
33,19.0,6,232.0,100.0,2634,13.0,71,usa,amc gremlin
160,17.0,6,231.0,110.0,3907,21.0,75,usa,buick century
252,19.2,6,231.0,105.0,3535,19.2,78,usa,pontiac phoenix lj
263,17.7,6,231.0,165.0,3445,13.4,78,usa,buick regal sport coupe (turbo)
226,20.5,6,231.0,105.0,3425,16.9,77,usa,buick skylark
363,22.4,6,231.0,110.0,3415,15.8,81,usa,buick century
258,20.6,6,231.0,105.0,3380,15.8,78,usa,buick century special
280,21.5,6,231.0,115.0,3245,15.4,79,usa,pontiac lemans v6
164,21.0,6,231.0,110.0,3039,15.0,75,usa,buick skyhawk
163,18.0,6,225.0,95.0,3785,19.0,75,usa,plymouth fury
199,20.0,6,225.0,100.0,3651,17.7,76,usa,dodge aspen se
227,19.0,6,225.0,100.0,3630,17.7,77,usa,plymouth volare custom
260,18.6,6,225.0,110.0,3620,18.7,78,usa,dodge aspen
135,18.0,6,225.0,105.0,3613,16.5,74,usa,plymouth satellite sebring
366,17.6,6,225.0,85.0,3465,16.6,81,usa,chrysler lebaron salon
34,16.0,6,225.0,105.0,3439,15.5,71,usa,plymouth satellite custom
256,20.5,6,225.0,100.0,3430,17.2,78,usa,plymouth volare
316,19.1,6,225.0,90.0,3381,18.7,80,usa,dodge aspen
284,20.6,6,225.0,110.0,3360,16.6,79,usa,dodge aspen 6
152,19.0,6,225.0,95.0,3264,16.0,75,usa,plymouth valiant custom
191,22.0,6,225.0,100.0,3233,15.4,76,usa,plymouth valiant
97,18.0,6,225.0,105.0,3121,16.5,73,usa,plymouth valiant
253,20.5,6,200.0,95.0,3155,18.2,78,usa,chevrolet malibu
259,20.8,6,200.0,85.0,3070,16.7,78,usa,mercury zephyr
365,20.2,6,200.0,88.0,3060,17.1,81,usa,ford granada gl
193,24.0,6,200.0,81.0,3012,17.6,76,usa,ford maverick
281,19.8,6,200.0,85.0,2990,18.2,79,usa,mercury zephyr 6
254,20.2,6,200.0,85.0,2965,15.8,78,usa,ford fairmont (auto)
17,21.0,6,200.0,85.0,2587,16.0,70,usa,ford maverick
16,18.0,6,199.0,97.0,2774,15.5,70,usa,amc hornet
24,21.0,6,199.0,90.0,2648,15.0,70,usa,amc gremlin
125,20.0,6,198.0,95.0,3102,16.5,74,usa,plymouth duster
101,23.0,6,198.0,95.0,2904,16.0,73,usa,plymouth duster
15,22.0,6,198.0,95.0,2833,15.5,70,usa,plymouth duster
297,25.4,5,183.0,77.0,3530,20.1,79,europe,mercedes benz 300d
386,25.0,6,181.0,110.0,2945,16.4,82,usa,buick century limited
341,23.5,6,173.0,110.0,2725,12.6,81,usa,chevrolet citation
307,26.8,6,173.0,115.0,2700,12.9,79,usa,oldsmobile omega brougham
306,28.8,6,173.0,115.0,2595,11.3,79,usa,chevrolet citation
174,18.0,6,171.0,97.0,2984,14.5,75,usa,ford pinto
211,16.5,6,168.0,120.0,3820,16.7,76,europe,mercedes-benz 280s
333,32.7,6,168.0,132.0,2910,11.4,80,japan,datsun 280-zx
361,25.4,6,168.0,116.0,2900,12.6,81,japan,toyota cressida
277,16.2,6,163.0,133.0,3410,15.8,78,europe,peugeot 604sl
275,17.0,6,163.0,125.0,3140,13.6,78,europe,volvo 264gl
210,19.0,6,156.0,108.0,2930,15.5,76,japan,toyota mark ii
123,20.0,6,156.0,122.0,2807,13.5,73,japan,toyota mark ii
323,27.9,4,156.0,105.0,2800,14.4,80,usa,dodge colt
271,23.2,4,156.0,105.0,2745,16.7,78,usa,plymouth sapporo
340,25.8,4,156.0,92.0,2620,14.4,81,usa,dodge aries wagon (sw)
388,26.0,4,156.0,92.0,2585,14.5,82,usa,chrysler lebaron medallion
113,21.0,6,155.0,107.0,2472,14.0,73,usa,mercury capri v6
315,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
392,27.0,4,151.0,90.0,2950,17.3,82,usa,chevrolet camaro
272,23.8,4,151.0,85.0,2855,17.6,78,usa,oldsmobile starfire sx
234,24.5,4,151.0,88.0,2740,16.0,77,usa,pontiac sunbird coupe
372,27.0,4,151.0,90.0,2735,18.0,82,usa,pontiac phoenix
313,28.0,4,151.0,90.0,2678,16.5,80,usa,chevrolet citation
305,28.4,4,151.0,90.0,2670,16.0,79,usa,buick skylark limited
339,26.6,4,151.0,84.0,2635,16.4,81,usa,buick skylark
308,33.5,4,151.0,90.0,2556,13.2,79,usa,pontiac phoenix
328,30.0,4,146.0,67.0,3250,21.8,80,europe,mercedes-benz 240d
362,24.2,6,146.0,120.0,2930,13.8,81,japan,datsun 810 maxima
241,22.0,6,146.0,97.0,2815,14.5,77,japan,datsun 810
360,30.7,6,145.0,76.0,3160,19.6,81,europe,volvo diesel
390,32.0,4,144.0,96.0,2665,13.9,82,japan,toyota celica gt
359,28.1,4,141.0,80.0,3230,20.4,81,europe,peugeot 505s turbo diesel
299,27.2,4,141.0,71.0,3190,24.8,79,europe,peugeot 504
282,22.3,4,140.0,88.0,2890,17.3,79,usa,ford fairmont 4
314,26.4,4,140.0,88.0,2870,18.1,80,usa,ford fairmont
373,24.0,4,140.0,92.0,2865,16.4,82,usa,ford fairmont futura
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
236,25.5,4,140.0,89.0,2755,15.8,77,usa,ford mustang ii 2+2
255,25.1,4,140.0,88.0,2720,15.4,78,usa,ford fairmont (man)
168,23.0,4,140.0,83.0,2639,17.0,75,usa,ford pinto
170,23.0,4,140.0,78.0,2592,18.5,75,usa,pontiac astro
184,25.0,4,140.0,92.0,2572,14.9,76,usa,capri ii
206,26.5,4,140.0,72.0,2565,13.6,76,usa,ford pinto
132,25.0,4,140.0,75.0,2542,17.0,74,usa,chevrolet vega
46,22.0,4,140.0,72.0,2408,19.0,71,usa,chevrolet vega (sw)
60,20.0,4,140.0,90.0,2408,19.5,72,usa,chevrolet vega
109,21.0,4,140.0,72.0,2401,19.5,73,usa,chevrolet vega
30,28.0,4,140.0,90.0,2264,15.5,71,usa,chevrolet vega 2300
371,29.0,4,135.0,84.0,2525,16.0,82,usa,dodge aries se
338,27.2,4,135.0,84.0,2490,15.7,81,usa,plymouth reliant
342,30.0,4,135.0,84.0,2385,12.9,81,usa,plymouth reliant
391,36.0,4,135.0,84.0,2370,13.0,82,usa,dodge charger 2.2
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
318,29.8,4,134.0,90.0,2711,15.5,80,japan,toyota corona liftback
171,24.0,4,134.0,96.0,2702,13.5,75,japan,toyota corona
267,27.5,4,134.0,95.0,2560,14.2,78,japan,toyota corona
270,21.1,4,134.0,95.0,2515,14.8,78,japan,toyota celica gt liftback
274,20.3,5,131.0,103.0,2830,15.9,78,europe,audi 5000
207,20.0,4,130.0,102.0,3150,15.7,76,europe,volvo 245
335,35.0,4,122.0,88.0,2500,15.1,80,europe,triumph tr7 coupe
130,26.0,4,122.0,80.0,2451,16.5,74,usa,ford pinto
80,22.0,4,122.0,86.0,2395,16.0,72,usa,ford pinto (sw)
112,19.0,4,122.0,85.0,2310,18.5,73,usa,ford pinto
219,25.5,4,122.0,96.0,2300,15.5,77,usa,plymouth arrow gs
61,21.0,4,122.0,86.0,2226,16.5,72,usa,ford pinto runabout
49,23.0,4,122.0,86.0,2220,14.0,71,usa,mercury capri 2000
327,36.4,5,121.0,67.0,2950,19.9,80,europe,audi 5000s (diesel)
179,22.0,4,121.0,98.0,2945,14.5,75,europe,volvo 244dl
76,18.0,4,121.0,112.0,2933,14.5,72,europe,volvo 145e (sw)
120,19.0,4,121.0,112.0,2868,15.5,73,europe,volvo 144ea
276,21.6,4,121.0,115.0,2795,15.7,78,europe,saab 99gle
180,25.0,4,121.0,115.0,2671,13.5,75,europe,saab 99le
296,27.4,4,121.0,80.0,2670,15.0,79,usa,amc spirit dl
122,24.0,4,121.0,110.0,2660,14.0,73,europe,saab 99le
242,21.5,4,121.0,110.0,2600,12.8,77,europe,bmw 320i
77,22.0,4,121.0,76.0,2511,18.0,72,europe,volkswagen 411 (sw)
23,26.0,4,121.0,113.0,2234,12.5,70,europe,bmw 2002
209,19.0,4,120.0,88.0,3270,21.9,76,europe,peugeot 504
78,21.0,4,120.0,87.0,2979,19.5,72,europe,peugeot 504 (sw)
178,23.0,4,120.0,88.0,2957,17.0,75,europe,peugeot 504
358,31.6,4,120.0,74.0,2635,18.3,81,japan,mazda 626
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
319,31.3,4,120.0,75.0,2542,17.5,80,japan,mazda 626
82,23.0,4,120.0,97.0,2506,14.5,72,japan,toyouta corona mark ii (sw)
149,24.0,4,120.0,97.0,2489,15.0,74,japan,honda civic
380,36.0,4,120.0,88.0,2160,14.5,82,japan,nissan stanza xe
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10
357,32.9,4,119.0,100.0,2615,14.8,81,japan,datsun 200sx
173,24.0,4,119.0,97.0,2545,17.0,75,japan,datsun 710
320,37.0,4,119.0,92.0,2434,15.0,80,japan,datsun 510 hatchback
273,23.9,4,119.0,97.0,2405,14.9,78,japan,datsun 200-sx
268,27.2,4,119.0,97.0,2300,14.7,78,japan,datsun 510
148,26.0,4,116.0,75.0,2246,14.0,74,europe,fiat 124 tc
183,25.0,4,116.0,81.0,2220,16.9,76,europe,opel 1900
118,24.0,4,116.0,75.0,2158,15.5,73,europe,opel manta
50,28.0,4,116.0,90.0,2123,14.0,71,europe,opel 1900
177,23.0,4,115.0,95.0,2694,15.0,75,europe,audi 100ls
119,20.0,4,114.0,91.0,2582,14.0,73,europe,audi 100ls
14,24.0,4,113.0,95.0,2372,15.0,70,japan,toyota corona mark ii
57,24.0,4,113.0,95.0,2278,15.5,72,japan,toyota corona hardtop
31,25.0,4,113.0,95.0,2228,14.0,71,japan,toyota corona
368,27.0,4,112.0,88.0,2640,18.6,82,usa,chevrolet cavalier wagon
367,28.0,4,112.0,88.0,2605,19.6,82,usa,chevrolet cavalier
370,31.0,4,112.0,85.0,2575,16.2,82,usa,pontiac j2000 se hatchback
369,34.0,4,112.0,88.0,2395,18.0,82,usa,chevrolet cavalier 2-door
217,30.0,4,111.0,80.0,2155,14.8,77,usa,buick opel isuzu deluxe
20,25.0,4,110.0,87.0,2672,17.5,70,europe,peugeot 504
150,26.0,4,108.0,93.0,2391,15.5,74,japan,subaru
110,22.0,4,108.0,94.0,2379,16.5,73,japan,datsun 610
356,32.4,4,108.0,75.0,2350,16.8,81,japan,toyota corolla
321,32.2,4,108.0,75.0,2265,15.2,80,japan,toyota corolla
382,34.0,4,108.0,70.0,2245,16.9,82,japan,toyota corolla
182,28.0,4,107.0,86.0,2464,15.5,76,europe,fiat 131
21,24.0,4,107.0,90.0,2430,14.5,70,europe,audi 100 ls
337,32.4,4,107.0,72.0,2290,17.0,80,japan,honda accord
355,33.7,4,107.0,75.0,2210,14.4,81,japan,honda prelude
381,36.0,4,107.0,75.0,2205,14.5,82,japan,honda accord
269,30.9,4,105.0,75.0,2230,14.5,78,usa,dodge omni
350,34.7,4,105.0,63.0,2215,14.9,81,usa,plymouth horizon 4
301,34.2,4,105.0,70.0,2200,13.2,79,usa,plymouth horizon
353,33.0,4,105.0,74.0,2190,14.2,81,europe,volkswagen jetta
302,34.5,4,105.0,70.0,2150,14.9,79,usa,plymouth horizon tc3
378,38.0,4,105.0,63.0,2125,14.7,82,usa,plymouth horizon miser
375,36.0,4,105.0,74.0,1980,15.3,82,europe,volkswagen rabbit l
22,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
186,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
352,29.9,4,98.0,65.0,2380,20.7,81,usa,ford escort 2h
114,26.0,4,98.0,90.0,2265,15.5,73,europe,fiat 124 sport coupe
185,26.0,4,98.0,79.0,2255,17.7,76,usa,dodge colt
141,29.0,4,98.0,83.0,2219,16.5,74,europe,audi fox
83,28.0,4,98.0,80.0,2164,15.0,72,usa,dodge colt (sw)
196,24.5,4,98.0,60.0,2164,22.1,76,usa,chevrolet woody
266,30.0,4,98.0,68.0,2155,16.5,78,usa,chevrolet chevette
309,41.5,4,98.0,76.0,2144,14.7,80,europe,vw rabbit
279,29.5,4,98.0,68.0,2135,16.6,78,japan,honda accord lx
379,36.0,4,98.0,70.0,2125,17.3,82,usa,mercury lynx l
311,32.1,4,98.0,70.0,2120,15.5,80,usa,chevrolet chevette
238,33.5,4,98.0,83.0,2075,15.9,77,usa,dodge colt m/m
237,30.5,4,98.0,63.0,2051,17.0,77,usa,chevrolet chevette
216,31.5,4,98.0,68.0,2045,18.5,77,japan,honda accord cvcc
351,34.4,4,98.0,65.0,2045,16.2,81,usa,ford escort 4w
295,35.7,4,98.0,80.0,1915,14.4,79,usa,dodge colt hatchback custom
245,36.1,4,98.0,66.0,1800,14.4,78,usa,ford fiesta
58,25.0,4,97.5,80.0,2126,17.0,72,usa,dodge colt hardtop
143,26.0,4,97.0,78.0,2300,14.5,74,europe,opel manta
81,28.0,4,97.0,92.0,2288,17.0,72,japan,datsun 510 (sw)
108,20.0,4,97.0,88.0,2279,19.0,73,japan,toyota carina
235,26.0,4,97.0,75.0,2265,18.2,77,japan,toyota corolla liftback
59,23.0,4,97.0,54.0,2254,23.5,72,europe,volkswagen type 3
240,30.5,4,97.0,78.0,2190,14.1,77,europe,volkswagen dasher
317,34.3,4,97.0,78.0,2188,15.8,80,europe,audi 4000
167,29.0,4,97.0,75.0,2171,16.0,75,japan,toyota corolla
205,28.0,4,97.0,75.0,2155,16.4,76,japan,toyota corolla
331,33.8,4,97.0,67.0,2145,18.0,80,japan,subaru dl
18,27.0,4,97.0,88.0,2130,14.5,70,japan,datsun pl510
29,27.0,4,97.0,88.0,2130,14.5,71,japan,datsun pl510
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
84,27.0,4,97.0,88.0,2100,16.5,72,japan,toyota corolla 1600 (sw)
346,32.3,4,97.0,67.0,2065,17.8,81,japan,subaru
239,30.0,4,97.0,67.0,1985,16.4,77,japan,subaru dl
102,26.0,4,97.0,46.0,1950,21.0,73,europe,volkswagen super beetle
233,29.0,4,97.0,78.0,1940,14.5,77,europe,volkswagen rabbit custom
19,26.0,4,97.0,46.0,1835,20.5,70,europe,volkswagen 1131 deluxe sedan
55,27.0,4,97.0,60.0,1834,19.0,71,europe,volkswagen model 111
203,29.5,4,97.0,71.0,1825,12.2,76,europe,volkswagen rabbit
79,26.0,4,96.0,69.0,2189,18.0,72,europe,renault 12 (sw)
304,37.3,4,91.0,69.0,2130,14.7,79,europe,fiat strada custom
376,37.0,4,91.0,68.0,2025,18.2,82,japan,mazda glc custom l
385,38.0,4,91.0,67.0,1995,16.2,82,japan,datsun 310 gx
349,34.1,4,91.0,68.0,1985,16.0,81,japan,mazda glc 4
377,31.0,4,91.0,68.0,1970,17.6,82,japan,mazda glc custom
383,38.0,4,91.0,67.0,1965,15.0,82,japan,honda civic
384,32.0,4,91.0,67.0,1965,15.7,82,japan,honda civic (auto)
56,26.0,4,91.0,70.0,1955,20.5,71,usa,plymouth cricket
329,44.6,4,91.0,67.0,1850,13.8,80,japan,honda civic 1500 gl
248,36.1,4,91.0,60.0,1800,16.4,78,japan,honda civic cvcc
181,33.0,4,91.0,53.0,1795,17.5,75,japan,honda civic cvcc

In [ ]:
car.T

,0,1,2,3,4,5,6,7,8,9,...,388,389,390,391,392,393,394,395,396,397
mpg,18.0,15.0,18.0,16.0,17.0,15.0,14.0,14.0,14.0,15.0,...,26.0,22.0,32.0,36.0,27.0,27.0,44.0,32.0,28.0,31.0
cylinders,8,8,8,8,8,8,8,8,8,8,...,4,6,4,4,4,4,4,4,4,4
displacement,307.0,350.0,318.0,304.0,302.0,429.0,454.0,440.0,455.0,390.0,...,156.0,232.0,144.0,135.0,151.0,140.0,97.0,135.0,120.0,119.0
horsepower,130.0,165.0,150.0,150.0,140.0,198.0,220.0,215.0,225.0,190.0,...,92.0,112.0,96.0,84.0,90.0,86.0,52.0,84.0,79.0,82.0
weight,3504,3693,3436,3433,3449,4341,4354,4312,4425,3850,...,2585,2835,2665,2370,2950,2790,2130,2295,2625,2720
acceleration,12.0,11.5,11.0,12.0,10.5,10.0,9.0,8.5,10.0,8.5,...,14.5,14.7,13.9,13.0,17.3,15.6,24.6,11.6,18.6,19.4
model_year,70,70,70,70,70,70,70,70,70,70,...,82,82,82,82,82,82,82,82,82,82
origin,usa,usa,usa,usa,usa,usa,usa,usa,usa,usa,...,usa,usa,japan,usa,usa,usa,europe,usa,usa,usa
name,chevrolet chevelle malibu,buick skylark 320,plymouth satellite,amc rebel sst,ford torino,ford galaxie 500,chevrolet impala,plymouth fury iii,pontiac catalina,amc ambassador dpl,...,chrysler lebaron medallion,ford granada l,toyota celica gt,dodge charger 2.2,chevrolet camaro,ford mustang gl,vw pickup,dodge rampage,ford ranger,chevy s-10

Practice Exercise 3

In [ ]:
import pandas as pd
titanic = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Titanic.csv')

In [ ]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

In [ ]:
titanic.name

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

In [ ]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [ ]:
name = titanic['name']

In [ ]:
name

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

In [ ]:
name = titanic[['name']]

In [ ]:
name

                                                 name
0                       Allen, Miss. Elisabeth Walton
1                      Allison, Master. Hudson Trevor
2                        Allison, Miss. Helen Loraine
3                Allison, Mr. Hudson Joshua Creighton
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
...                                               ...
1304                             Zabour, Miss. Hileni
1305                            Zabour, Miss. Thamine
1306                        Zakarian, Mr. Mapriededer
1307                              Zakarian, Mr. Ortin
1308                               Zimmerman, Mr. Leo

[1309 rows x 1 columns]

In [ ]:
titanic.iloc[100,:]

pclass                                                  1
survived                                                1
name         Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")
sex                                                  male
age                                                  49.0
sibsp                                                   1
parch                                                   0
ticket                                           PC 17485
fare                                              56.9292
cabin                                                 A20
embarked                                                C
boat                                                    1
body                                                  NaN
home.dest                                  London / Paris
Name: 100, dtype: object

In [ ]:
titanic.loc[100,:]

pclass                                                  1
survived                                                1
name         Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")
sex                                                  male
age                                                  49.0
sibsp                                                   1
parch                                                   0
ticket                                           PC 17485
fare                                              56.9292
cabin                                                 A20
embarked                                                C
boat                                                    1
body                                                  NaN
home.dest                                  London / Paris
Name: 100, dtype: object

In [ ]:
titanic.iloc[:,[2,8]]

                                                 name      fare
0                       Allen, Miss. Elisabeth Walton  211.3375
1                      Allison, Master. Hudson Trevor  151.5500
2                        Allison, Miss. Helen Loraine  151.5500
3                Allison, Mr. Hudson Joshua Creighton  151.5500
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  151.5500
...                                               ...       ...
1304                             Zabour, Miss. Hileni   14.4542
1305                            Zabour, Miss. Thamine   14.4542
1306                        Zakarian, Mr. Mapriededer    7.2250
1307                              Zakarian, Mr. Ortin    7.2250
1308                               Zimmerman, Mr. Leo    7.8750

[1309 rows x 2 columns]

In [ ]:
titanic.loc[:,['name','fare']]

                                                 name      fare
0                       Allen, Miss. Elisabeth Walton  211.3375
1                      Allison, Master. Hudson Trevor  151.5500
2                        Allison, Miss. Helen Loraine  151.5500
3                Allison, Mr. Hudson Joshua Creighton  151.5500
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  151.5500
...                                               ...       ...
1304                             Zabour, Miss. Hileni   14.4542
1305                            Zabour, Miss. Thamine   14.4542
1306                        Zakarian, Mr. Mapriededer    7.2250
1307                              Zakarian, Mr. Ortin    7.2250
1308                               Zimmerman, Mr. Leo    7.8750

[1309 rows x 2 columns]

In [ ]:
titanic.loc[[50,12,25],['pclass','fare','age']]

    pclass      fare   age
50       1  512.3292  58.0
12       1   69.3000  24.0
25       1   26.0000  25.0

In [ ]:
titanic.iloc[[50,12,25],[0,8,4]]

    pclass      fare   age
50       1  512.3292  58.0
12       1   69.3000  24.0
25       1   26.0000  25.0

In [ ]:
titanic.loc[10:25,['pclass','fare','age']]

    pclass      fare   age
10       1  227.5250  47.0
11       1  227.5250  18.0
12       1   69.3000  24.0
13       1   78.8500  26.0
14       1   30.0000  80.0
15       1   25.9250   NaN
16       1  247.5208  24.0
17       1  247.5208  50.0
18       1   76.2917  32.0
19       1   75.2417  36.0
20       1   52.5542  37.0
21       1   52.5542  47.0
22       1   30.0000  26.0
23       1  227.5250  42.0
24       1  221.7792  29.0
25       1   26.0000  25.0

In [ ]:
titanic.iloc[10:25,[0,8,4]]

    pclass      fare   age
10       1  227.5250  47.0
11       1  227.5250  18.0
12       1   69.3000  24.0
13       1   78.8500  26.0
14       1   30.0000  80.0
15       1   25.9250   NaN
16       1  247.5208  24.0
17       1  247.5208  50.0
18       1   76.2917  32.0
19       1   75.2417  36.0
20       1   52.5542  37.0
21       1   52.5542  47.0
22       1   30.0000  26.0
23       1  227.5250  42.0
24       1  221.7792  29.0

In [ ]:
titanic.loc[10:15,['pclass', 'age']]

    pclass   age
10       1  47.0
11       1  18.0
12       1  24.0
13       1  26.0
14       1  80.0
15       1   NaN

In [ ]:
titanic.iloc[10:16, 0:5]

,pclass,survived,name,sex,age
10,1,0,"Astor, Col. John Jacob",male,47.0
11,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.0
12,1,1,"Aubart, Mme. Leontine Pauline",female,24.0
13,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0
14,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0
15,1,0,"Baumann, Mr. John D",male,NaN

In [ ]:
titanic[titanic['age']>=35]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,NaN,22.0,"Montevideo, Uruguay"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,C,NaN,NaN
1287,3,0,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S,NaN,NaN,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,NaN,NaN,NaN
1298,3,0,"Wittevrongel, Mr. Camille",male,36.0,0,0,345771,9.5000,NaN,S,NaN,NaN,NaN
1301,3,0,"Youseff, Mr. Gerious",male,45.5,0,0,2628,7.2250,NaN,C,NaN,312.0,NaN

In [ ]:
titanic.loc[(titanic['age']>=35),'pclass':'age']

,pclass,survived,name,sex,age
5,1,1,"Anderson, Mr. Harry",male,48.0
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0
9,1,0,"Artagaveytia, Mr. Ramon",male,71.0
...,...,...,...,...,...
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0
1287,3,0,"Widegren, Mr. Carl/Charles Peter",male,51.0
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0
1298,3,0,"Wittevrongel, Mr. Camille",male,36.0
1301,3,0,"Youseff, Mr. Gerious",male,45.5

In [ ]:
titanic.loc[(titanic['age']>=35)&(titanic['sex']=='female')]

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"
17,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C,6,NaN,"Montreal, PQ"
21,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,5,NaN,"New York, NY"
23,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C,4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1158,3,0,"Rosblom, Mrs. Viktor (Helena Wilhelmina)",female,41.0,0,2,370129,20.2125,NaN,S,NaN,NaN,NaN
1211,3,0,"Skoog, Mrs. William (Anna Bernhardina Karlsson)",female,45.0,1,4,347088,27.9000,NaN,S,NaN,NaN,NaN
1261,3,1,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,15,NaN,NaN
1286,3,1,"Whabee, Mrs. George Joseph (Shawneene Abi-Saab)",female,38.0,0,0,2688,7.2292,NaN,C,C,NaN,NaN
1290,3,1,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,NaN,NaN,NaN

Practice Exercise 4

In [ ]:
tips = pd.read_csv('https://github.com/YBI-Foundation/Dataset/raw/main/Tips%20Payment%20Data.csv')

In [ ]:
tips

,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971320,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685990,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637220,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052840,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565400,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747190,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698130,Thur672

In [ ]:
tips.head()

,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971320,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685990,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637220,Sun2251

In [ ]:
tips['Tip']/tips['Total Bill']*100

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

In [ ]:
tips_percentage=tips['Tip']/tips['Total Bill']*100

In [ ]:
tips_percentage

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

In [ ]:
tips['tips_percentage']=tips['Tip']/tips['Total Bill']*100

In [ ]:
tips

,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,Payer Name,CC Number,Payment ID,tips_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971320,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685990,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637220,Sun2251,14.680765
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052840,Sat2657,20.392697
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565400,Sat1766,7.358352
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747190,Sat3880,8.822232
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.820426
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698130,Thur672,15.974441

In [ ]:
tips['tips_percentage']= tips['tips_percentage'].round(1)

In [ ]:
tips

,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,Payer Name,CC Number,Payment ID,tips_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.9
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.1
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971320,Sun4458,16.7
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685990,Sun5260,14.0
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637220,Sun2251,14.7
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052840,Sat2657,20.4
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565400,Sat1766,7.4
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747190,Sat3880,8.8
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17,9.8
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698130,Thur672,16.0

In [ ]:
tips= tips.drop(['Payer Name'],axis =1 )

In [ ]:
tips

,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,CC Number,Payment ID,tips_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,Sun2959,5.9
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,Sun4608,16.1
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971320,Sun4458,16.7
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685990,Sun5260,14.0
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637220,Sun2251,14.7
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052840,Sat2657,20.4
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565400,Sat1766,7.4
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747190,Sat3880,8.8
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,Sat17,9.8
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698130,Thur672,16.0

In [ ]:
tips = tips.set_index('Payment ID')

In [ ]:
tips

,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,CC Number,tips_percentage
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.9
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.1
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971320,16.7
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685990,14.0
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637220,14.7
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052840,20.4
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565400,7.4
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747190,8.8
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,9.8
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698130,16.0

In [ ]:
tips = tips.reset_index()

In [ ]:
tips

,Payment ID,Total Bill,Tip,Gender,Smoker,Day,Time,Size,Bill Per Person,CC Number,tips_percentage
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,3560325168603410,5.9
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,4478071379779230,16.1
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,6011812112971320,16.7
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,4676137647685990,14.0
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,4832732618637220,14.7
...,...,...,...,...,...,...,...,...,...,...,...
239,Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,5296068606052840,20.4
240,Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,3506806155565400,7.4
241,Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,6011891618747190,8.8
242,Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,4375220550950,9.8
243,Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,3511451626698130,16.0

In [ ]:
titanic.corr()

            pclass  survived       age     sibsp     parch      fare      body
pclass    1.000000 -0.312469 -0.408106  0.060832  0.018322 -0.558629 -0.034642
survived -0.312469  1.000000 -0.055512 -0.027825  0.082660  0.244265       NaN
age      -0.408106 -0.055512  1.000000 -0.243699 -0.150917  0.178740  0.058809
sibsp     0.060832 -0.027825 -0.243699  1.000000  0.373587  0.160238 -0.099961
parch     0.018322  0.082660 -0.150917  0.373587  1.000000  0.221539  0.051099
fare     -0.558629  0.244265  0.178740  0.160238  0.221539  1.000000 -0.043110
body     -0.034642       NaN  0.058809 -0.099961  0.051099 -0.043110  1.000000

In [ ]:
titanic['age'].nlargest(2)

14    80.0
61    76.0
Name: age, dtype: float64

In [ ]:
titanic['age'].nsmallest(2)

763    0.17
747    0.33
Name: age, dtype: float64

In [ ]:
titanic['age'].max()

80.0

In [ ]:
titanic['age'].min()

0.17

In [ ]:
titanic['pclass'].astype('object')

0       1
1       1
2       1
3       1
4       1
       ..
1304    3
1305    3
1306    3
1307    3
1308    3
Name: pclass, Length: 1309, dtype: object

In [ ]:
titanic['pclass']=titanic['pclass'].astype('object')

In [ ]:
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [ ]:
titanic['embarked'].nunique()

3

In [ ]:
titanic['embarked'].unique()

array(['S', 'C', nan, 'Q'], dtype=object)

In [ ]:
titanic['embarked'].value_counts()

S    914
C    270
Q    123
Name: embarked, dtype: int64

In [ ]:
titanic.replace({'sex':{'male':0,'female':1}})

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",1,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",0,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",1,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",0,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",1,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",1,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",0,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",0,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",0,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [ ]:
titanic.replace({'sex':{'male':0,'female':1}}, inplace =True)

In [ ]:
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",1,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",0,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",1,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",0,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",1,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",1,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",1,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",0,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",0,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",0,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN